### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Default weather id is different from what SA:MP uses

### ISSUE THREAD

**Issue by VictorMacielGhost** [openmultiplayer/server-beta-old#1]
# Description

* The World Color Is Different From SA:MP Server

# Idk if is a bug or new feature, but the world are more purple, stranger maybe

*Tell us a how to re-produce this behavior:*

Maybe SetWorldTime. Idk exactly

# open.mp server version

* 0.3.7-R2 open.mp server

# Windows 

# Contact information

* Victor Ghost#9449 vtbolado17@gmail.com or fluxorjrp@gmailc.com

* Images
SA:MP Server
![image](https://user-images.githubusercontent.com/87531280/164303763-854eb5ad-6531-453a-8745-00aad5e5ddcb.png)

open.mp Server:
![image](https://user-images.githubusercontent.com/87531280/164303833-21b074fa-a1d9-4c04-a771-fe454889555f.png)

(ignore the footer, is script)

**Comment by Hual** [comment]
The default weather ID is different than the SA:MP server. Although this is a behaviour difference I'm not sure it's a bug since the default weather ID isn't defined in SA:MP

**Comment by AmyrAhmady** [comment]
Default is the same
in SA:MP if you set player's weather it doesn't work when it's called in OnPlayerConnect
we fixed that in open.mp, so it could be this case, closing this
