### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Modes are still loaded if the rcon password isn't changed

### ISSUE THREAD

**Issue by Y-Less** [openmultiplayer/server-beta-old#108]
# Description

If you forget to change the rcon password in the config file the mode is still loaded after the error message.  This gives the impression that nothing is wrong, but the server ends abruptly.

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

1. *Step one*
2. *Step two*
3. *Step three*

# Relevant log output

```
*Paste your relevant log output here!*
```

# open.mp server version

*What open.mp server version are you using?

For a development build please specify its commit hash.*

# Operating system or distribution

*Tell us what operating system or distribution did you use when you did encounter this behavior difference?*

# Contact information

*ex. Username#1234 or email@example.com*

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by ksenonadv** [comment]
Fixed next build.
