### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: TRAILER SYNC

### ISSUE THREAD

**Issue by Locky0** [openmultiplayer/server-beta-old#110]
# Description

when towing a vehicle on the open-mp server, the trailer changes position. this does not happen on the sa-mp server.

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

1. Get a truck
2. Tow a trailer that is not correctly aligned
3. The trailer will line up by itself.

# Relevant log output
No errors in log

# open.mp server version

beta5

# Operating system or distribution

Windows 10 / Linux Debian

# Contact information

Locky#5912

# Additional information

This happens even without implementing callback OnTrailerUpdate, that is, even in the script this happens.

**Comment by ksenonadv** [comment]
Trailer sync works just fine - tested on a live server.
The server reattaches the trailer from time to time to fix a desyncing issue for remote players.
