### ISSUE TITLE
[BUG]: Specific SendClientMessage and CreateExplosion combination breaks player camera

### ISSUE THREAD

**Issue by Zbyss** [openmultiplayer/server-beta-old#111]
# Description

This sounds ridiculous, but running the code below a few times [causes a shaking camera effect for the player](https://streamable.com/ehp5tg), until he dies. The order does matter, creating the explosion first and then sending the client message works fine, and it happens only with specific strings in the client message (from my observations, it must contain at least one colour embed).

**Note:** This works for some reason only with SA:MP Addon. I would consider it as some regular bug related to modded client, but it doesn't happen on SA:MP server.

# How to re-produce this bug

Paste this code in a command or sth and run it **a few times** (it doesn't always work the first time).
```pawn
new Float:x, Float:y, Float:z;
GetPlayerPos(playerid, x, y, z);

SendClientMessage(playerid, -1, "{FFFFFF}1234567890123456");
CreateExplosion(x, y, z, 2, 50.0);
```

# Relevant log output

N/A

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

Microsoft Windows 11 64-bit

# Contact information

Zbyss.#2597

# Additional information

N/A

**Comment by mrreus** [comment]
I've tested that and got the same results.

**Comment by AmyrAhmady** [comment]
Fixed in build 6
