### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: strins()

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta-old#112]
# Description

The strins() function does not truncate the size of the to be inserted string like SA-MP does.

# How to re-produce this behavior difference

```Pawn
#include <a_samp>
#include <streamer>
#include <zcmd>


main() { }

CMD:test(playerid, const params[])
{
	new info[1024], str[128];
	for(new i = 0; i < 20; i++)
	{
		format(str, sizeof(str), "%d: %s \n", i + 1, "Testing string");
		strins(info, str, strlen(info), sizeof(str));
	}
	ShowPlayerDialog(playerid, 0, DIALOG_STYLE_LIST, "------------", info, "Yes", "No");
	return 1;
}
```

# Relevant log output

### open.mp server
![sa-mp-268](https://user-images.githubusercontent.com/54376805/175797325-f8ee3b30-4821-4430-bb73-31f80b2c9bbb.png)
### SA-MP server
![sa-mp-269](https://user-images.githubusercontent.com/54376805/175797326-d4aee2a0-9f1b-4ec9-8fa8-bbe08214290a.png)

# open.mp server version

open.mp server public beta build 5

# Operating system or distribution

Debian 11 & Windows 10

# Contact information

Richano#9220
rishanogopal@gmail.com

# Additional information
-

**Comment by ksenonadv** [comment]
The function is working properly unlike samp one. 
You're providing a wrong value for max_length param for your scenario - sizeof (str) which is 128. This will result in final string being truncated to 128 characters (127 + null terminator).
You need to set max_length param to size of final buffer - sizeof (info).
