### ISSUE TITLE
[BUG]: Using GangZoneShowForPlayer repeatedly creates multiple gangzones

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#115]
# Description

When using the GangZoneShowForPlayer function more than once with the same gangzone for the same player, it seems that more gangzones are created and GangZoneHideForPlayer does not work.

# How to re-produce this bug

1. Create a gangzone
2. Use GangZoneShowForPlayer 2 times or more
3. Try using GangZoneHideForPlayer, the gangzone will not disappear

# open.mp server version

*open.mp server public beta build 5*

# Operating system or distribution

*Windows 10*

**Comment by AmyrAhmady** [comment]
Fixed in build 6
