### ISSUE TITLE
[BUG]: NetStats_GetConnectedTime returning wrong value

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#116]
# Description

NetStats_GetConnectedTime is returning a random static value.

# How to re-produce this bug

See the value returned by NetStats_GetConnectedTime, it will be the same every time.

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

*Windows 10 and Debian 10*

**Comment by ksenonadv** [comment]
Duplicate of #107
