### ISSUE TITLE
[BUG]: InterpolateCameraPos function not working

### ISSUE THREAD

**Issue by lucasgama335** [openmultiplayer/server-beta-old#117]
# Description
on my login screen there is a subtle camera movement at the entrance, however in openmp it is not working

*Describe the bug you have encountered!*
the function to move the camera is not working in the current build

# How to re-produce this bug
`public OnPlayerConnect(playerid)
{
InterpolateCameraPos(playerid, 1430.3030, -1222.7921, 153.7742, 1430.2842, -1227.1599, 153.6056, 2000, CAMERA_MOVE);
		InterpolateCameraLookAt(playerid, 1430.7921, -1223.6633, 153.5791, 1431.1718, -1227.6151, 153.3904, 2000, CAMERA_MOVE);
}`

Just use the function

# Relevant log output

In OPENMP
https://i.postimg.cc/HHQLhR7h/sa-mp-000.png

IN SAMP
https://i.postimg.cc/nHDxQ94P/sa-mp-001.png
https://i.postimg.cc/pWQtsN1Q/sa-mp-002.png

# open.mp server version

build 5

For a development build please specify its commit hash.*

# Operating system or distribution

Windows 11

# Contact information

RhaegarX#1268

# Additional information
You can test directly from the gamemode I used: https://github.com/lucasgama335/newlife-server

**Comment by lucasgama335** [comment]
an interesting fact about this problem.  it usually only occurs on the first server startup, if you restart the server with gmx the camera moves back normally

**Comment by lucasgama335** [comment]
apparently the problem was being caused, because I was using the include "samp-fixes" and when I removed it the operation returned to normal

**Comment by AmyrAhmady** [comment]
@lucasgama335 Thanks for posting the problem and the issue causing it, it's really going to help us later
