### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: SetVehicleVelocity after vehicle creation

### ISSUE THREAD

**Issue by LDami** [openmultiplayer/server-beta-old#118]
# Description

When I call SetVehicleVelocity just after creating a vehicle and put player in driver seat, the velocity is not applied to the vehicle.
In SA-MP it works correctly, but in open.mp I have to add a timer of 100ms after PutPlayerInVehicle to apply the velocity.

# How to re-produce this behavior difference

```cpp
new Float:x, Float:y, Float:z;
GetPlayerPos(playerid, x, y, z);
new vID = CreateVehicle(411, x, y, z, 0, 1, 1, 100);
PutPlayerInVehicle(playerid, vID, 0);
SetVehicleVelocity(vID, 5.0, 0, 0);
```

# open.mp server version

0.0.0.0 build 5

# Operating system or distribution

Windows 10

# Contact information

LDami#8585

**Comment by ksenonadv** [comment]
Hello. 
Vehicle driver is not updated until the client syncs as because PutPlayerInVehicle might fail. 
We are not going to change this. 
You can correct your code by changing velocity in OnPlayerStateChange callback (newstate == PLAYER_STATE_DRIVER).
