### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Player markers

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta-old#119]
# Description

Player markers for unaffected players are streamed out for hidden players when they go out of streaming range. See snippet below.

# How to re-produce this behavior difference

1. Make sure both players are at blueberry. (/tpblueberry)
2. Use /hideme.
3. Use /tprichman (on the same player) to go out of stream range.

Result: omp-server does not stream the other player anymore which hasn't used the /hideme command, unlike samp-server.

```Pawn

#include <a_samp>
#include <zcmd>

main() { }

CMD:hideme(playerid, params[])
{
    for(new i = 0; i < MAX_PLAYERS; i++)
    {
    	if (IsPlayerConnected(i) && i != playerid)
    		SetPlayerMarkerForPlayer(i, playerid, (GetPlayerColor( playerid ) & 0xFFFFFF00));

    }
}

CMD:tprichman(playerid, params[]) SetPlayerPos(playerid,  293.6332, -1154.1692, 80.9099);
CMD:tpblueberry(playerid, params[]) SetPlayerPos(playerid, 0.0, 0.0, 4.0);

```
# Relevant log output

-

# open.mp server version

open.mp server public beta build 5

# Operating system or distribution

Debian 11 & Windows 10

# Contact information

Richano#9220
[rishanogopal@gmail.com](mailto:rishanogopal@gmail.com)

# Additional information

-

**Comment by ksenonadv** [comment]
Fixed next build.
