### ISSUE TITLE
[BUG]: omp-server.exe has stopped working

### ISSUE THREAD

**Issue by CEKIKOFGAMERS** [openmultiplayer/server-beta-old#12]
# Description

*Describe the bug you have encountered!*

# How to re-produce this bug

*Tell us a how to re-produce this bug in steps for example:*

1. *Run omp-server executable*
2. *connect*
3. *omp-server has stopped working*

# Relevant log output

```
[2022-04-21T03:56:35Z] [Info] Legacy Network started on port 7777
[2022-04-21T03:56:48Z] [Info] Failed to announce legacy network to open.mp list

```

# open.mp server version

Open MP build 1

For a development build please specify its commit hash.*

# Operating system or distribution

Windows 10 Pro

# Contact information

Kristoforus#8837/maga64613@gmail.com

**Comment by Y-Less** [comment]
We need a lot more information to reproduce this unfortunately.  What mode?  How many players?  Who?  etc.

**Comment by CEKIKOFGAMERS** [comment]
> We need a lot more information to reproduce this unfortunately. What mode? How many players? Who? etc.

1 Players

**Comment by Hual** [comment]
Do you have a .dmp file generated in your server root? If so, can you attach it here?

**Comment by Zhasulan5** [comment]
Same problem

**Comment by AmyrAhmady** [comment]
@Zhasulan5 @CEKIKOFGAMERS can any of you please give us more info?
or at least upload the generated .dmp file

**Comment by Zhasulan5** [comment]
> @Zhasulan5 @CEKIKOFGAMERSкто-нибудь из вас может дать нам больше информации? или хотя бы загрузите сгенерированный файл .dmp
[omp_minidump.zip](https://github.com/openmultiplayer/server-beta/files/8543203/omp_minidump.zip)

**Comment by AmyrAhmady** [comment]
@Zhasulan5 It seems like you are using Pawn.RakNet and Pawn.CMD, these two plugins are not supported, TOTP as well
![image](https://user-images.githubusercontent.com/34688664/164949227-504721a6-a95b-4c1d-aeda-277cb523da21.png)

Please update your server with latest beta build from here
https://github.com/openmultiplayer/server-beta/releases/tag/build2

**Comment by Zhasulan5** [comment]
@AmyrAhmady i have errors
![image](https://user-images.githubusercontent.com/80032123/164990655-4a362e66-b51b-4cd7-9237-fc660ac10ea4.png)

**Comment by AmyrAhmady** [comment]
@Zhasulan5 Yes, like I said, these two plugins are not supported and in order to your code work, you need them
We are in touch with creator of Pawn.RakNet, he already made Pawn.CMD
We will list every plugin that is ported to open.mp in this page, make sure you check it frequently :)
https://github.com/openmultiplayer/server-beta/blob/master/PLUGINLIST.md

**Comment by CEKIKOFGAMERS** [comment]
> @Zhasulan5 @CEKIKOFGAMERS can any of you please give us more info? or at least upload the generated .dmp file

[omp_minidump.zip](https://github.com/openmultiplayer/server-beta/files/8579221/omp_minidump.zip)
sorry for late send this dump file because my laptop charger has lost and i can't send dump file
