### ISSUE TITLE
[BUG]: DeletePVar native

### ISSUE THREAD

**Issue by eksqtr** [openmultiplayer/server-beta-old#120]
# Description
DeletePVar(playerid, varname); it doesn't delete the PVar variable, GetPVarType(playerid, pvar); still return as 1 not 0.
*Describe the bug you have encountered!*

# How to re-produce this bug
use t he SetPVarInt native and delete it using DeletePVar then use GetPVarType

*Tell us a how to re-produce this bug in steps for example:*

1. SetPVarInt(playerid, "test", 1);
2. DeletePVar(playerid, "test");
3. print("GetPVarType: %d", GetPVarType(playerid, "test")); // not returning to 0

# Relevant log output
N/A
```
[22:16:06] [Info] GetPVarType: 1
```
# open.mp server version 
beta build 5
*What open.mp server version are you using?

For a development build please specify its commit hash.*

# Operating system or distribution
Windows
*Tell us what operating system or distribution did you use when you did encounter this bug?*
Windows
# Contact information

*eksqtr@gmail.com*

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by ksenonadv** [comment]
Fixed next build.
