### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: SetPlayerTeam does not work in special cases

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta-old#121]
# Description

SetPlayerTeam does not work if used in a specific way, see snippet below. The server I'm working on has had a bug related to F4 making players stuck. The code below represents a slimmed down version of the fix I wrote. When porting to open.mp, this still functioned properly, but the SetPlayerTeam function in the OnPlayerSpawn public wasn't affecting the player teams for some reason.

# How to re-produce this behavior difference

1. Wait 5 seconds on joining, after which you will be spawned.
2. Use /getteam to check the team.

```Pawn
#define YSI_NO_HEAP_MALLOC

#include <a_samp>
#include <crashdetect>
#include <sscanf>
#include <YSI-Includes\YSI_Coding\y_inline>
#include <YSI-Includes\YSI_Data\y_iterate>
#include <YSI-Includes\YSI_Coding\y_hooks>
#include <zcmd>

main() { }

new OnPlayerSpawnTime[MAX_PLAYERS];

forward TimerCallback(playerid);

// Stop processing all next OnPlayerSpawn hooks & publics
hook OnPlayerSpawn(playerid)
{
	if(gettime() - OnPlayerSpawnTime[playerid] <= 1)
	{
		OnPlayerSpawnTime[playerid] = 0;
		return ~1;
	}
	else
	{
		OnPlayerSpawnTime[playerid] = gettime();
	}
	return 1;
}

public OnPlayerDeath(playerid, killerid, reason)
{
	OnPlayerSpawnTime[playerid] = 0;
}

public OnPlayerRequestClass(playerid)
{
	TogglePlayerSpectating(playerid, true);
   	SetSpawnInfo(playerid, 255, 0, 1466.4388,-1283.8247,14.5766, 5, 0, 0, 0, 0, 0, 0);

	SetTimerEx("TimerCallback", 5000, false, "d", playerid);
	return 1;
}

public OnPlayerSpawn(playerid)
{
	SendClientMessage(playerid, -1, "OnPlayerSpawn");
	SetPlayerPos(playerid, 293.6332, -1154.1692, 80.9099);
	SetPlayerTeam(playerid, 1);
	TogglePlayerControllable(playerid, true);
	return 1;
}

public TimerCallback(playerid)
{
	new modelid = 69;
	TogglePlayerSpectating(playerid, false);
  	SetSpawnInfo(playerid, 255, modelid, 758.9221,-2934.8364,-0.8094, 5, 0, 0, 0, 0, 0, 0);
	SetPlayerTeam(playerid, 255);
	SetPlayerSkin(playerid, modelid);
	SetPVarInt(playerid, "select_skin", 0);
	SpawnPlayer(playerid);
	return 1;
}

CMD:getteam(playerid, const params[])
{
	new str[128];
	format(str, sizeof(str), "team: %d", GetPlayerTeam(playerid));
	SendClientMessage(playerid, -1, str);
	return 1;
}
```

# Relevant log output

/getteam on omp-server gives teamid 255. (incorrect)
/getteam on samp-server gives teamid 1. (correct)

# open.mp server version

open.mp server public beta build 5

# Operating system or distribution

Debian 11 & Windows 10

# Contact information

Richano#9220
[rishanogopal@gmail.com](mailto:rishanogopal@gmail.com)

# Additional information

Inverting the if statement in the OnPlayerSpawn hook fixes the problem. Seems like the second call for OnPlayerSpawn does set the teams correctly.

**Comment by ksenonadv** [comment]
Fixed next build.
