### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: GetPlayerWeaponData always returns 0 ammo for slot 0

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#123]
# Description

GetPlayerWeaponData always returns 0 ammo for slot 0, even using SetPlayerAmmo, whereas in SA-MP it is possible to set ammo for slot 0. This is useful for detecting if the player is out of sync by switching ammo to 0 and 1.

# How to re-produce this behavior difference

Code I used to reproduce:

```
CMD:setammo(playerid)
{
	new weaponid, ammo;
	GetPlayerWeaponData(playerid, 0, weaponid, ammo);
	
	SetPlayerAmmo(playerid, weaponid, 1);
	return 1;
}

CMD:getammo(playerid)
{
	new weaponid, ammo;
	GetPlayerWeaponData(playerid, 0, weaponid, ammo);
	
	new str[129];
	format(str, sizeof(str), "Ammo: %d", ammo);
	SendClientMessage(playerid, -1, str);
	return 1;
}
```

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

Windows 10 and Debian 10

**Comment by ksenonadv** [comment]
Fixed next build.
