### ISSUE TITLE
[BUG]: TogglePlayerControllable continues after respawn

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#124]
# Description

If the player is frozen with TogglePlayerControllable and dies, they are unfrozen upon respawning. But to other players the player continues to appear as if frozen, moving without doing any animation. It's easy to fix in Pawn by putting `TogglePlayerControllable(playerid, true);` in OnPlayerSpawn.

# How to re-produce this bug

1. Freeze player using TogglePlayerControllable
2. Respawn or kill the player
3. See him walking

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

Windows 10 and Debian 10

**Comment by ksenonadv** [comment]
Fixed next build.
