### ISSUE TITLE
[BUG]: IsPlayerInAnyVehicle returning true after PutPlayerInVehicle fails

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#125]
# Description

If PutPlayerInVehicle fails to place the player in the vehicle, the player remains in the onfoot state but the IsPlayerInAnyVehicle and GetPlayerVehicleID functions continue to indicate that the player is in the vehicle. The bug continues until the player enters a vehicle or the vehicle is destroyed.

# How to re-produce this bug

It is possible to reproduce this bug with the command below, but it is also possible with some cheat that ignores the RPC PutPlayerInVehicle.

```
CMD:vcreate(playerid)
{
	SetPlayerSpecialAction(playerid, SPECIAL_ACTION_DRINK_BEER);
	
	new Float:x, Float:y, Float:z;
	GetPlayerPos(playerid, x, y, z);
	
	new vehicleid = CreateVehicle(411, x, y, z, 0.0, -1, -1, 100);
	
	PutPlayerInVehicle(playerid, vehicleid, 0);
	return 1;
}

CMD:vinfo(playerid)
{
	new str[128];
	format(str, sizeof(str), "vID: %d | State: %d | InAnyVeh: %d", GetPlayerVehicleID(playerid), GetPlayerState(playerid), IsPlayerInAnyVehicle(playerid));
	
	SendClientMessage(playerid, -1, str);
	return 1;
}
```

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

Windows 10

**Comment by ksenonadv** [comment]
Fixed next build.
