### ISSUE TITLE
[BUG]: Spectator appearing paused near the spectated player

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#126]
# Description

Sometimes when using PlayerSpectatePlayer or PlayerSpectateVehicle the spectator appears paused next to the player being spectated. In the case of PlayerSpectateVehicle, the skin appears in the middle of the vehicle and can even damage or stop it.

Demo video: https://www.youtube.com/watch?v=nrY8wcwoRJM

# How to re-produce this bug

Starting and stopping spectating a player, always waiting for the player to stream out.

NOTE: I always used these functions immediately after TogglePlayerSpectating.

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

Windows 10 and Debian 10

**Comment by ksenonadv** [comment]
Fixed next build.
