### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Incorrect behavior of function TextDrawSetPreviewRot when X value goes over 90 degrees

### ISSUE THREAD

**Issue by dev-karpov0** [openmultiplayer/server-beta-old#127]
# Description

Incorrect behavior of function `TextDrawSetPreviewRot` when X value goes over 90 degrees.
Object rotates to a big angle when X changing from 89 to 90 and 90 to 91 degrees.

# How to re-produce this behavior difference

See attachments
![sa-mp-010](https://user-images.githubusercontent.com/52952604/177995763-1a2d6d23-db55-4a52-afee-e37c7397ebcc.png)

# open.mp server version
beta build 5

# Operating system or distribution

Windows 10

# Contact information

dev.karpov0@gmail.com

**Comment by ksenonadv** [comment]
Fixed in build 6.

**Comment by AmyrAhmady** [comment]
This is fixed in next build, will be available soon
