### ISSUE TITLE
[BUG]: Crashdump when server ended

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#131]
# Description

Just started one of basic GMs for a quick test, tested all what I needed and tried to close the server console. After waiting for some time (a little bit longer than when all is ok) it was closed and a .dmp file was created in the folder.

I used only pawnraknet (as a component) and streamer plugin, if it's important anyhow.
Could provide the whole archive with gamemode if requested, but I hope the minidump should be enough.

# Relevant log output

Log file didn't print anything special, but here's minidump created:
[omp_minidump.zip](https://github.com/openmultiplayer/server-beta/files/9080138/omp_minidump.zip)

# open.mp server version

[Build 6](https://github.com/openmultiplayer/server-beta/releases/tag/build6) (after updating Fixes.dll component)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
The issue is from Pawn.RakNet component. 
It needs to be patched there.
