### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: TogglePlayerSpectating false calling OnPlayerStateChange

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#132]
# Description

When using `TogglePlayerSpectating(playerid, false);` on a player that is not in state spectating, the OnPlayerStateChange callback is called twice with newstate = 9 and oldstate = 1 and then vice versa. In SA-MP the callback is not called in this case.

# How to re-produce this behavior difference

Code:
```
public OnPlayerStateChange(playerid, newstate, oldstate)
{
	new str[128];
	format(str, sizeof(str), "OnPlayerStateChange(%d, %d, %d)", playerid, newstate, oldstate);
	SendClientMessage(playerid, -1, str);
	return 1;
}

CMD:specoff(playerid)
{
	TogglePlayerSpectating(playerid, false);
	return 1;
}
```

Output after using /specoff:
```
OnPlayerStateChange(0, 9, 1)
OnPlayerStateChange(0, 1, 9)
```

# open.mp server version

[open.mp server public beta build 6](https://github.com/openmultiplayer/server-beta/releases/tag/build6)

# Operating system or distribution

Windows 10 and Debian 10

# Contact information

Rodrigo#7685

**Comment by ksenonadv** [comment]
Fixed next build.
