### ISSUE TITLE
[BUG]: Vehicle does not stream-out when using SetPlayerVirtualWorld

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#134]
# Description

Vehicle does not stream-out when using SetPlayerVirtualWorld.

Demo video: https://www.youtube.com/watch?v=egZnGNZw078

# How to re-produce this bug

1. Drive a vehicle
2. Use SetPlayerVirtualWorld
3. Vehicle will not stream out until you exit it

# open.mp server version

[open.mp server public beta build 6](https://github.com/openmultiplayer/server-beta/releases/tag/build6)

# Operating system or distribution

Windows 10 and Debian 10

# Contact information

Rodrigo#7685

**Comment by ksenonadv** [comment]
Fixed next build.
