### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: OnGameModeExit call order

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#137]
# Description

OnGameModeExit always called first in gamemode just like OnGameModeInit in samp server, but omp server calls it in filterscripts first.

# How to re-produce this behavior difference

1. Create one filterscript and a gamemode.

2. Put this into fs, compile:
```pawn
#include <a_samp>

public OnGameModeExit()
{
	print("[FS] OnGameModeExit called");
	return 1;
}
```

3. Put this into gm, compile:
```pawn
#include <a_samp>

main(){}

public OnGameModeExit()
{
	print("[GM] OnGameModeExit called");
	return 1;
}
```

# Relevant log output

samp server
```
Console input: exit
[15:24:46] --- Server Shutting Down.
[15:24:46] [GM] OnGameModeExit called
[15:24:46] [FS] OnGameModeExit called
```

omp server
```
[15:24:42] [Info] [FS] OnGameModeExit called
[15:24:42] [Info] [GM] OnGameModeExit called
```

# open.mp server version

[Build 6](https://github.com/openmultiplayer/server-beta/releases/tag/build6) (after updating Fixes.dll component)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
Fixed next build.
