### ISSUE TITLE
[BUG]: Interpolate Camera Moving bug

### ISSUE THREAD

**Issue by Sancky** [openmultiplayer/server-beta-old#14]
# Description

InterpolateCameraPos / InterpolateCameraLookAt are not working when the player is in spectate mode

# How to re-produce this bug

```
public OnPlayerConnect(playerid) 
{
	TogglePlayerSpectating(playerid, true);
		
	InterpolateCameraPos(playerid, 370.658172, -1398.887207, 101.570533, 530.287475, -1413.706054, 87.225357, 15000);
	InterpolateCameraLookAt(playerid, 374.464080, -1400.969604, 99.084770, 528.010192, -1416.861450, 84.085639, 15000);
	return 1;
}
```

# Relevant log output

```
-
```

# open.mp server version

build 1

# Operating system or distribution

Windows 10 64-bit

# Contact information

Sancky#3199

# Additional information

-

**Comment by ksenonadv** [comment]
Fixed next build.
