### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: IsPlayerInAnyVehicle wrong return

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta-old#141]
# Description

Entering a vehicle as passenger in the rear seats, specifically in a vehicle with the Merit model (551), does not flag as being in its passenger seats. IsPlayerInAnyVehicle returns 0. Haven't checked yet if it happens with other specific vehicles, but for now it only happens with this specific model.

# How to re-produce this behavior difference

```Pawn
#include <a_samp>
#include <zcmd>

CMD:spawnveh(playerid, const params[])
{
	new Float:pX, Float:pY, Float:pZ;
	GetPlayerPos(playerid, pX, pY, pZ);
	CreateVehicle(551, pX, pY, pZ, 0.0, -1, -1, -1); // spawn merit
	return 1;
}

CMD:getveh(playerid, const params[])
{
	new string[32];
	format(string, sizeof(string), "Is in any vehicle: %d", IsPlayerInAnyVehicle(playerid));
	SendClientMessage(playerid, -1, string);
	return 1;
}
```
1. /spawnveh
2. Enter as passenger in rear seats
3. /getveh

# Relevant log output

/getveh on samp-server gives "Is in any vehicle: 1".
/getveh on omp-server gives "Is in any vehicle: 0".

# open.mp server version

open.mp server public beta build 7

# Operating system or distribution

Debian 11 & Windows 10

# Contact information

Richano#9220
rishanogopal@gmail.com

# Additional information

-

**Comment by AmyrAhmady** [comment]
It was fixed in build7, after talking to @RichanoG he mentioned he was accidentally using build5
