### ISSUE TITLE
[BUG]: [Beta 7] --dump-config creates incomplete config.json

### ISSUE THREAD

**Issue by xerox8521** [openmultiplayer/server-beta-old#145]
# Description

If the server is run with --dump-config and there is no server.cfg present it will generate a default config.json which is missing the "pawn" part where legacy_plugins, gamemode and filterscripts are specified.

# How to re-produce this bug

Download Beta 7
Run omp-server.exe with --dump-config
Check config.json

# open.mp server version

Beta 7 https://github.com/openmultiplayer/server-beta/commit/2ba3cb1a1e87afbf7a14a892bd12066308950224

# Operating system or distribution

Windows 10 Pro 64 Bit

# Contact information

XeroX#5204

# Additional information
Left side shows --dump-config and right side shows --default-config. No server.cfg was present when running these commands.
https://www.diffchecker.com/XgXTuQK2

Looking at the diff link it seems that bot_exe is missing when creating a config file with --default-config.

**Comment by AmyrAhmady** [comment]
As it is clearly mentioned here https://github.com/openmultiplayer/server-beta/releases/tag/build6

and also here:
https://github.com/openmultiplayer/server-beta#configuration

--dump-config uses server.cfg, so I'm not sure what you were expecting when you used it without one
Closing this as this is not an issue

**Comment by xerox8521** [comment]
Imho it should still create a **usable** config file if it cannot find a server.cfg which can happen if for example you run the command by accident first before inserting the server.cfg file.

**Comment by AmyrAhmady** [comment]
There's a reason we have --default-config and --dump-config, the fact that --dump-config even works without server.cfg is already a mistake
has the name in it, it dumps currently filled configuration values, and if there is none and you get nothing, just use --default-config
