### ISSUE TITLE
[BUG]: Cannot properly read some legacy config settings

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#146]
# Description

At least `lagcompmode` legacy setting from server.cfg cannot be properly read by the omp server, always returning 0 even if it was enabled. At the same time, some others like `minconnectiontime` works fine. I didn't tested all types (string, int, bool, float) and all config parameters, just lagcompmode, but I suppose there are probably some more which currently broken for some reason.

# How to re-produce this bug

```pawn
public OnGameModeInit()
{
	printf("lagcomp is %d", GetConsoleVarAsInt("lagcompmode"));
	return 1;
}
```

# Relevant log output

samp server:
```
[00:22:56] lagcomp is 1
```

omp server:
```
[00:23:06] [Info] lagcomp is 0
```

# open.mp server version

[Build 7](https://github.com/openmultiplayer/server-beta/releases/tag/build7)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by AmyrAhmady** [comment]
Fixed in build 8
