### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: SetGameModeText makes the server browser silently fail when the string passed is 40+ char

### ISSUE THREAD

**Issue by ZantetsukenGT** [openmultiplayer/server-beta-old#149]
# Description

*When using SetGameModeText with a 30+ char string:*

**SA-MP**: truncates it to 30char

**open.mp**: won't truncate and if the string is 40+ char the client server browser will silently fail to set the gamemode text and subsequent settings like Language

# How to re-produce this behavior difference

1. on open.mp
```pawn
#include <a_samp>
main() {}
public OnGameModeInit()
{
    // the server browser fails to set the string and won't set Language either
    // length: 40
    SetGameModeText("1234567890123456789012345678901234567890");

    // the server browser won't fail
    // length: 39
    //SetGameModeText("123456789012345678901234567890123456789");
}
```

2. Look at your client server browser after starting the server.

# Relevant log output

```
*No output*
```

# open.mp server version

*beta 7*

# Operating system or distribution

*Debian testing and Windows*

# Contact information

*Zantetsuken#2220*

# Additional information

*--*

**Comment by AmyrAhmady** [comment]
Fixed in build 8
