### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: OnRconCommand behaviour when command not found

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#151]
# Description

When every filterscript and gamemode has OnRconCommand and returning 0 if command was not found in case of samp server, it behaves like OnPlayerCommandText, sending the message `Unknown command or variable: <text>` in the server console instead of `RCON (In-Game): Player [Player_Name] sent command: <text>` message. Omp server always sends only the last message even if the command wasn't found, not indicating success or failure of the callback execution. Might be good to add the first message just to make it more clear & behave it logging more like samp server.

# How to re-produce this behavior difference

Return 0 in OnRconCommand (in both fs and gm), enter the game, login into RCon and type random /rcon \<command\> which doesn't exist.

# open.mp server version

[Build 7](https://github.com/openmultiplayer/server-beta/releases/tag/build7)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
Fixed next build.
