### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Wider Menus

### ISSUE THREAD

**Issue by Jexuul** [openmultiplayer/server-beta-old#152]
# Description

*Describe the behavior difference between open.mp server and SA:MP server!*
Menus are wider on open.mp than samp

# How to re-produce this behavior difference
new Menu:Ammo[0];
Ammo[0] = CreateMenu("Ammo-Nation", 1, 30.0, 150.0, 190.0, 180.0);
	AddMenuItem(Ammo[0], 0, "Pistols");
	AddMenuItem(Ammo[0], 0, "Micro Smgs");
	AddMenuItem(Ammo[0], 0, "Shotgun");
	AddMenuItem(Ammo[0], 0, "Armour");
	AddMenuItem(Ammo[0], 0, "Smg");
	AddMenuItem(Ammo[0], 0, "Assault");
	AddMenuItem(Ammo[0], 0, "Rifles");
	AddMenuItem(Ammo[0], 0, "Parachute");

CMD:ammo(playerid, params[])
{
ShowMenuForPlayer(playerid, Ammo[0]);
return 1;
}

samp
https://prnt.sc/MurvV72aKUG5

open.mp
https://prnt.sc/qHg6Vlwn7EcK

# open.mp server version

https://github.com/openmultiplayer/server-beta/releases/tag/build7

# Operating system or distribution

Windows 10  (21H2)

# Contact information

Jex#7909

# Additional information
None

**Comment by ksenonadv** [comment]
Fixed next build.
