### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: SetSpawnInfo does nothing on a REALLY INSIGNIFICANT particular case

### ISSUE THREAD

**Issue by Marevin** [openmultiplayer/server-beta-old#153]
# Description
On open.mp, SetSpawnInfo spawns the player on 0,0,0 while on SA:MP it spawns the player on the correct given location with the correct weapons.

# How to re-produce this behavior difference
Using SetSpawnInfo in OnPlayerRequestClass, on a bare new gamemode with NO AddPlayerClass.
If AddPlayerClass is present, the behavior on both servers is the same (SetSpawnInfo is ignored).

# open.mp server version
beta 7 windows

# Operating system or distribution
Win10 Home

# Contact information
@Marevin

**Comment by ksenonadv** [comment]
Fixed next build.
