### ISSUE TITLE
[BUG]: Kick(playerid); Kick(playerid); clears chat before disconnecting

### ISSUE THREAD

**Issue by BY-KILLIGAN** [openmultiplayer/server-beta-old#155]
# Description

Kick(playerid); clears chat before disconnecting

*Tell us a how to re-produce this bug in steps for example:*

1. Use the Kick(playerid);

# open.mp server version

[open.mp server public beta build 7](https://github.com/openmultiplayer/server-beta/releases/tag/build7)

# Operating system or distribution

Windows

# Contact information

KILLIGAN#6659

**Comment by ksenonadv** [comment]
Closing this. Can't repro it.
If you think there's a bug please open this again with a script which can be used to reproduce your issue.
