### ISSUE TITLE
[BUG]: IsVehicleOccupied native is bugged

### ISSUE THREAD

**Issue by lPauI** [openmultiplayer/server-beta-old#158]
*Describe the bug you have encountered!*

IsVehicleOccupied is returning true also if is no one in vehicle.

*Tell us a how to re-produce this bug in steps for example:*

1. Use SetPlayerPos to a player who is in a vehicle.

*What open.mp server version are you using?

omp build 8

For a development build please specify its commit hash.*

*Tell us what operating system or distribution did you use when you did encounter this bug?*

linux debian 11

xPaulFTW#4537

*Any additional information that could be relevant for us to know?*

No.

**Comment by ksenonadv** [comment]
Fixed next build.
