### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: 'Unknown command or variable' for both console and in-game rcon

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#161]
# Description

Previously added warning about unknown rcon command now works for any of the cases: when a player type something via in-game rcon, when a server owner write in the server console and when a script call it via `SendRconCommand`. Original SA-MP server throw such warning in the server console and for player only if the command was typed in the chat by player via in-game rcon. It would be nice to see this warning when in-game admins type unknown commands and when it is sent by remote rcon connected to the server, but not by scripts or/and by user input of some text in the server console. The last option could be kept as it is now, but logging the warning message every time when a random pawn script uses SendRconCommand for non-existent ones (by a typo mistake or more often intentionally, as we can see from the latest discord complaints) seems redundant.

# How to re-produce this behavior difference

Use `SendRconCommand` with random text for some internal purpose or without any.

# open.mp server version

[Build 8](https://github.com/openmultiplayer/server-beta/releases/tag/build8)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
There's nothing wrong with server warning if there's a script attempting to call invalid commands.
We find it helpful. 
It can help people understand why scripts are failing when there's a typo.
