### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Dialog is not showed before kicking player

### ISSUE THREAD

**Issue by xunder-matth** [openmultiplayer/server-beta-old#162]
# Description

Showing dialog before kicking player (with delay) is very inconsistent. Most of the times dialog is not showed.

# How to re-produce this behavior difference

```
forward DoYouSeeThis();
public DoYouSeeThis() {
    ShowPlayerDialog(0, 0, DIALOG_STYLE_MSGBOX, "Test dialog", "Hello!", "OK", "Quit");
    SetTimer("DelayedKick", 50, false);
}

forward DelayedKick();
public DelayedKick() {
    Kick(0);
}

public OnPlayerConnect(playerid) {
    SetTimer("DoYouSeeThis", 100, true);
    return 1;
}
```

# Relevant log output

# open.mp server version

[open.mp build 8](https://github.com/openmultiplayer/server-beta/releases/tag/build8)

# Operating system or distribution

Tested on Ubuntu 20.04 and Ubuntu 18.04.

# Contact information

Xunder#4936

# Additional information

**Comment by xunder-matth** [comment]
![dialogbug](https://user-images.githubusercontent.com/28492178/185710249-8a318a24-6cad-4de5-bc9b-f1cb6e06a33f.png)

**Comment by ksenonadv** [comment]
Use a higher interval.

**Comment by xs1vr** [comment]
> Use a higher interval.

Yeah, that's totally how ur gonna get biggest server's like his to switch, lame..

**Comment by Hual** [comment]
> > Use a higher interval.
> 
> Yeah, that's totally how ur gonna get biggest server's like his to switch, lame..

We can't do miracles with the samp protocol

**Comment by xs1vr** [comment]
> > > Use a higher interval.
> > 
> > 
> > Yeah, that's totally how ur gonna get biggest server's like his to switch, lame..
> 
> We can't do miracles with the samp protocol

I believe he's already been using it like this since forever if he opened this issue, he ain't a noob

**Comment by AmyrAhmady** [comment]
@xslvrxslwt I have already talked to both developers of Skill Arena, if you really do know them, you can talk to them, ask what they think about this issue, not you

**Comment by xs1vr** [comment]
> 

I asked him now, sorry, should've done so before

edit: btw I'm not being mad cuz of i.e. 100ms rather than 50ms but rather worried on why is it behaving like that if 50ms was enough for samp (i assumed it was because xunder opened the issue (shouldn't have gone with this attitude anyway, overreacted sorry))

**Comment by Hual** [comment]
> I asked him now, sorry, should've done so before
> 
> edit: btw I'm not being mad cuz of i.e. 100ms rather than 50ms but rather worried on why is it behaving like that if 50ms was enough for samp (i assumed it was because xunder opened the issue)

The fact that you're mad about anything is enough for me not to bother explaining

**Comment by xs1vr** [comment]
> > I asked him now, sorry, should've done so before
> > edit: btw I'm not being mad cuz of i.e. 100ms rather than 50ms but rather worried on why is it behaving like that if 50ms was enough for samp (i assumed it was because xunder opened the issue)
> 
> The fact that you're mad about anything is enough for me not to bother explaining

Bad English bud, I said I wasn't mad but worried xd (e: or at least that's what I meant, mb)

**Comment by Hual** [comment]
> > > I asked him now, sorry, should've done so before
> > > edit: btw I'm not being mad cuz of i.e. 100ms rather than 50ms but rather worried on why is it behaving like that if 50ms was enough for samp (i assumed it was because xunder opened the issue)
> > 
> > 
> > The fact that you're mad about anything is enough for me not to bother explaining
> 
> Bad English bud, I said I wasn't mad but worried xd (e: or at least that's what I meant, mb)

Alright, so when you base your networking on real world timing (like the order here), something is bound to break sooner or later when you change the system

**Comment by xs1vr** [comment]
> > > > I asked him now, sorry, should've done so before
> > > > edit: btw I'm not being mad cuz of i.e. 100ms rather than 50ms but rather worried on why is it behaving like that if 50ms was enough for samp (i assumed it was because xunder opened the issue)
> > > 
> > > 
> > > The fact that you're mad about anything is enough for me not to bother explaining
> > 
> > 
> > Bad English bud, I said I wasn't mad but worried xd (e: or at least that's what I meant, mb)
> 
> Alright, so when you base your networking on real world timing (like the order here), something is bound to break sooner or later when you change the system

Yes, that's what I supposed as well, but still had to check haha (as there's no source as of yet and it's already mid 2022 (not blaming you just yk everyone (was) a bit sceptical ab the project)

ik I've gone a bit harder than I've should with my shitty attitude lol, sorry once again

**Comment by Cheaterman** [comment]
> Alright, so when you base your networking on real world timing (like the order here), something is bound to break sooner or later when you change the system

Especially if you replace said system with a version that performs better (ie changes the general "real world timing" characteristics). Nothing worrying, in fact perhaps a bit encouraging since the goal was to make open.mp better all along.

**Comment by xs1vr** [comment]
> > Alright, so when you base your networking on real world timing (like the order here), something is bound to break sooner or later when you change the system
> 
> Especially if you replace said system with a version that performs better (ie changes the general "real world timing" characteristics). Nothing worrying, in fact perhaps a bit encouraging since the goal was to make open.mp better all along.

<3
