### ISSUE TITLE
[BUG]: Player vehicle id are not update if teleport player from vehicle

### ISSUE THREAD

**Issue by Abyss-z94** [openmultiplayer/server-beta-old#163]
# Description
Player vehicle id are not update if teleport player from vehicle.

*Describe the bug you have encountered!*
GetPlayerVehicleID(playerid) return ID 0 always.

# How to re-produce this bug
If a player inside a vehicle (Driver or Passenger seat) and teleport to another position (without exit vehicle), the function GetPlayerVehicle(playerid) alway return ID 0 when he re-enter a vehicle on Driver Seat. 

*Tell us a how to re-produce this bug in steps for example:*

1. Get in any Vehicle as a Driver or Passenger
2. SetPlayerPos(playerid, x, y, z) to any position.
3. Re-enter any vehicle as Driver and check with printf GetPlayerVehicleID(playerid).

If player re-enter vehicle with passenger, this bug disappear.

# Relevant log output
https://youtu.be/tE-KJzz6peg

*Paste your relevant log output here!*
[20:49:27] Vehicle ID: 1 // On step 1.
[20:49:39] Vehicle ID: 0 // This is the result after step 3
```

# open.mp server version

*What open.mp server version are you using? Beta Build 8

For a development build please specify its commit hash.*

# Operating system or distribution

*Tell us what operating system or distribution did you use when you did encounter this bug?* Windows

# Contact information

*JJs#0020*

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by AmyrAhmady** [comment]
Fixed in build 9
