### ISSUE TITLE
[BUG]: IsPlayerInAnyVehicle failing

### ISSUE THREAD

**Issue by xunder-matth** [openmultiplayer/server-beta-old#165]
# Description

Sometimes `IsPlayerInAnyVehicle` is failing although player is in vehicle.

# How to re-produce this bug

I don't really know. It seems to me like it's happening randomly.

# Relevant log output

Video: https://youtu.be/l_JL0FF6EQ8

I will provide explanation in "Additional information"

# open.mp server version

open.mp build 8

# Operating system or distribution

Ubuntu 18.04

# Contact information

Xunder#4936

# Additional information

Player is typing command `/izlaz` (which means `/exit` on Serbian) which triggers `IsPlayerInAnyVehicle` and if player is not in vehicle command will return `SendClientMessage` informing player he's not in vehicle (Output: `{YELLOW}[SA:RP] {GREY}Morate biti u vozilu.`).
In video we can see that player is clearly in vehicle (on bike) and command server is telling him he's not.
Note that red/tomato error chat message is anti spam and it's not related to issue.

I'm having multiple complains about this bug but we recorded only one video, however I will try to get more videos of this happening.
If there is any debugging we can do on our end please inform me via Discord private message.

**Comment by xunder-matth** [comment]
Probably related to #163.

**Comment by AmyrAhmady** [comment]
Fixed in build 9
