### ISSUE TITLE
[BUG]: Checkpoints

### ISSUE THREAD

**Issue by TandaraAdrian** [openmultiplayer/server-beta-old#168]
Hello, I discovered a bug in the native SetPlayerCheckpoint, when you set another checkpoint after verifying that you entered the first created checkpoint, you automatically enter the 2nd checkpoint when you first entered the first created checkpoint. I made a code example below.

https://pastebin.com/NEa7372v

**Comment by Y-Less** [comment]
Those are in the same position, so the player should enter the second one, because they're now inside it.

**Comment by Y-Less** [comment]
Does this happen when the second checkpoint isn't placed on top of the player?

**Comment by TandaraAdrian** [comment]
In the example above, yes, it is, but I have 2 different positions in gamemode, for example: https://pastebin.com/Yq8Mc9aF

**Comment by TandaraAdrian** [comment]
More precisely, there are 2 checkpoints, 3 and 4, and when I enter checkpoint 3, I also enter 4 automatically, without me entering with the character.

**Comment by TandaraAdrian** [comment]
I managed to solve this problem by making a timer of one second where I set the other checkpoint, so the problem may be that it is set too quickly or I don't know.

**Comment by ksenonadv** [comment]
> In the example above, yes, it is, but I have 2 different positions in gamemode, for example: https://pastebin.com/Yq8Mc9aF

The issue is your code. You need to use else if or to return after you set ```CP[playerid] = 4;```
