### ISSUE TITLE
[BUG]: Dialogs not working on omp-server but on samp-server works perfectly

### ISSUE THREAD

**Issue by sunkie25** [openmultiplayer/server-beta-old#17]
# Description

I opened an omp-server after I moved all needed files from old samp server folder, all good. When I joined the omp server and I tried to login nothing happened. I tried also on the samp server, it worked perfectly. I modified in the script to log in without entering a password, it worked, but when I wanted to buy something from /shop or /buy nothing happened. More info at "# How to re-produce this bug".

# How to re-produce this bug

https://www.youtube.com/watch?v=DZOeN1UMqyk

*Tell us a how to re-produce this bug in steps for example:*

1.  I started the server and I joined.
2.  I tested a few commands that use dialogs.
3.  Nothing happened, I tried on the basic samp server and it worked perfectly.

# Relevant log output

```
No log.
```

# open.mp server version

*What open.mp server version are you using?

open.mp build 1

# Operating system or distribution

Windows 10 x64

# Contact information

Discord: irinel77#3505

# Additional information

None.

**Comment by Y-Less** [comment]
https://github.com/openmultiplayer/server-beta/issues/5

https://github.com/openmultiplayer/server-beta/issues/11

Already fixed.
