### ISSUE TITLE
[BUG]: Trailer sync bug

### ISSUE THREAD

**Issue by xunder-matth** [openmultiplayer/server-beta-old#170]
# Description

The video says it all.
https://youtu.be/8tQNR5V6Y5M

# How to re-produce this bug

1. Get in vehicle
2. Attach a trailer
3. Don't move

# open.mp server version

open.mp build 8

# Operating system or distribution

Linux

# Contact information

Xunder#4936

# Additional information

**Comment by ksenonadv** [comment]
Is the trailer attached via native (AttachTrailerToVehicle) or by the game?

**Comment by xunder-matth** [comment]
> Is the trailer attached via native (AttachTrailerToVehicle) or by the game?

By the game.

**Comment by ksenonadv** [comment]
Should be fixed in build9.
