### ISSUE TITLE
[BUG]:  beta 8 ackslimit  in config.json

### ISSUE THREAD

**Issue by mixedthoughts** [openmultiplayer/server-beta-old#172]
# Config.json file, on beta 8 openmp ackslimit

kicks you from the server for exceeding ackslimit 3000.

Did not happen on beta 5. It seems it doesn't detect what's written in config.json on beta 8 build.

[2022-08-28T10:59:53Z] [Warning] client exceeded 'ackslimit' 54.62.40.19:61418 (3114) Limit: 3000/sec

config.json:
{
    "ackslimit": 30000,

**Comment by ksenonadv** [comment]
The option was changed in build6. 
Generate a new config.json
