### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Cabbie 

### ISSUE THREAD

**Issue by mixedthoughts** [openmultiplayer/server-beta-old#173]
Cabbie vehicle, id 6: type 438,
says "no car" as vehicle name once you enter it +  OnPlayerEnterVehicle/OnPlayerStateChange is not detected for this vehicle, no dialogs popping up.

But for cabbie id : 7/8  & type 438, everything is fine.

doesn't happen in sa-mp.
![sa-mp-007](https://user-images.githubusercontent.com/111257922/187067603-6c2081a2-4fe9-4fd2-9e8b-89e11d065f50.png)

**Comment by AmyrAhmady** [comment]
Use the issue templates and provide requested info so we can understand and reproduce this bug, create a new again.
