### ISSUE TITLE
[BUG]: SetSpawnInfo does not work on NPC's correctly

### ISSUE THREAD

**Issue by Pun1sh3r94** [openmultiplayer/server-beta-old#174]
# Description

Use SetSpawnInfo on a NPC, doesnt set the Skin on Windows, use SetPlayerSkin works fine after SetSpawnInfo on Windows but the same code doesnt seems to be working on Linux.

public OnPlayerRequestClass(playerid, classid)
{
    if(IsPlayerNPC(playerid))
    {
        new playername[64];    GetPlayerName(playerid,playername,64);
        if(!strcmp(playername,"TrainDriver",true))
        {
            SetSpawnInfo(playerid,69,255,1462.0745,2630.8787,10.8203,0.0,-1,-1,-1,-1,-1,-1);
            bla1 = Create3DTextLabel("TrainDriver NPC Bot",COLOR_GREEN,30.0,40.0,90.0,50,0,0);
            SetPlayerSkin(playerid, 255);
            PutPlayerInVehicleSync(playerid,TrainCar,0);
            SetPlayerColor(playerid, RGBAToHexaDecimal(random(255), random(255), random(255), 255));
            Attach3DTextLabelToPlayer(bla1, playerid, 0.0,0.0,0.0);
        }
}
return 1;
}
SetSpawnInfo doesnt set the Skin and using SetPlayerSkin seems to be working for the NPC but the same code doesnt work on Linux

# open.mp server version

build 8

# Operating system or distribution

Windows 10 Build: 19044.1826
Linux Debian 10

# Contact information

Contact me on Discord: Pun1sh3r#3221

# Additional information

-

**Comment by ksenonadv** [comment]
Fixed next build.
