### ISSUE TITLE
[BUG]: DisableRemoteVehicleCollisions

### ISSUE THREAD

**Issue by m1ronzy** [openmultiplayer/server-beta-old#177]
# Description

*Describe the bug you have encountered!*

In SA:MP 0.3.7 introduced the function of disabling collisions for vehicles. But, if the transport is with a trailer, then there is a collision on the trailer. Is it possible to implement the refinement of the function with the disabling of the collision on transport with a trailer?

*Tell us a how to re-produce this bug in steps for example:*

new string[64];
format(string, sizeof(string), "Vehicle collision for you is now '%s'", (GetPVarInt(playerid, "vehCollision") != 1) ? ("Disabled") : ("Enabled"));
SendClientMessage(playerid, 0xFFFFFFFF, string);
SetPVarInt(playerid, "vehCollision", !GetPVarInt(playerid, "vehCollision"));
DisableRemoteVehicleCollisions(playerid, GetPVarInt(playerid, "vehCollision"));

# Relevant log output

```
-
```

# open.mp server version

build 8

# Operating system or distribution

Windows, Linux

# Contact information

M1RoN#6464

# Additional information

-

**Comment by Alasnkz** [comment]
This is for server bugs not function enhancements relating to the client.
