### ISSUE TITLE
[BUG]: Character Freezes

### ISSUE THREAD

**Issue by nexquery** [openmultiplayer/server-beta-old#18]
# Description

If a player uses the SetSpawnInfo and SpawnPlayer functions while connecting to the server, the character will freeze.

# How to re-produce this bug

1. *Create a simple game mode.*
```c
#include <a_samp>

main()
{

}

public OnPlayerConnect(playerid)
{
    SetSpawnInfo(playerid, NO_TEAM, 289, -33.3565, 200.4222, 2.4297, 354.9867, 31, 30, 0, 0, 0, 0);
    SpawnPlayer(playerid);
    return 1;
}
```
2. *Connect to the server.*
3. *And see the character freeze.*

# Relevant log output

```
N/A
```

# open.mp server version

[open.mp server public beta build 1](https://github.com/openmultiplayer/server-beta/releases/tag/build1)

# Operating system or distribution

Windows 10 Home

# Contact information

Nexor#4730

# Additional information

N/A

**Comment by AmyrAhmady** [comment]
Fixed, will be available in build4
