### ISSUE TITLE
[BUG]: Wrong encoding of a console command that wasn't found

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#180]
# Description

Wrong encoding of a console command typed in cyrillic if it wasn't found, when it prints a error with it.

# How to re-produce this bug

Start the server and type some non-latin chars.

# Relevant log output

![image](https://user-images.githubusercontent.com/13169094/188324774-352fd272-97da-4985-9eaa-7deb0d2f7730.png)

# open.mp server version

[Build 8](https://github.com/openmultiplayer/server-beta/releases/tag/build8)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by AmyrAhmady** [comment]
Fixed in next build
