### ISSUE TITLE
[BUG]: Attach trailer

### ISSUE THREAD

**Issue by m1ronzy** [openmultiplayer/server-beta-old#181]
# Description

It is impossible to pick up a trailer on mapping territories
[*video*](https://www.youtube.com/watch?v=pshvMNOgha0)

# How to re-produce this bug

*Tell us a how to re-produce this bug in steps for example:*

1. Get in vehicle
2. Try to hook up a trailer

# open.mp server version

build 8

# Operating system or distribution

Debian 10.12

# Contact information

M1RoN#6464

**Comment by m1ronzy** [comment]
But, if the player is not in the truck, then the trailer can be picked up using AttachTrailerToVehicle

**Comment by ksenonadv** [comment]
Fixed in build9.
