### ISSUE TITLE
[BUG]: GetPlayerVehicleID wrong return value

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta-old#183]
# Description

Combining GetPlayerVehicleID, and SetPlayerPos (see code snippet) causes GetPlayerVehicleID to return wrong values when used in a specific way. GetPlayerVehicleID will return 0 when returning wrong values.

# How to re-produce this bug

1. Spawn
2. Enter hydra & wait for the server to eject you
3. Enter hydra again
4. Debug messages indicate a difference in vehicle id

```Pawn
#include <a_samp>

main() {}

public OnGameModeInit()
{
	AddStaticVehicleEx(520, 0.0, 0.0, 3.3, 235.8314,0,0,1200); // Spawn hydra
	return 1;
}

public OnPlayerStateChange(playerid, newstate, oldstate)
{
	new vehicleID = GetPlayerVehicleID(playerid),
		vehicleid = vehicleID;

	if (newstate == PLAYER_STATE_DRIVER)
	{
		new string[64];
		format(string, sizeof(string),  "vehicle id: %d", vehicleid);
		SendClientMessage(playerid, -1, string);
		SendClientMessage(playerid, -1,"Removing player from vehicle");
		RemovePlayerFromVehicleEx(playerid);
		return 1;
	}
	return 1;
}

stock RemovePlayerFromVehicleEx(playerid)
{
	if (gettime() - GetPVarInt(playerid, "InteriorChange") > 2) // Will always be true
	{
		new Float:X, Float:Y, Float:Z;
		GetPlayerPos(playerid, X, Y, Z);
		SetPlayerPos(playerid,X,Y,Z);
	}
	else
	{
		RemovePlayerFromVehicle(playerid);
	}
	return 1;
}
```

# Relevant log output

```
-- Enter hydra 1st time
vehicle id: 1
Removing player from vehicle

-- Enter hydra 2nd time
vehicle id: 0
Removing player from vehicle
```

# open.mp server version

open.mp server public beta build 8

# Operating system or distribution

Debian 11

# Contact information

Richano#9220
[rishanogopal@gmail.com](mailto:rishanogopal@gmail.com)

# Additional information

FYI, it does not happen with just the hydra, it happens with multiple vehicles models which probably indicates it isn't vehicle model specifc afaik.

**Comment by ksenonadv** [comment]
Fixed in build9.
