### ISSUE TITLE
[BUG]: Connected NPCs didn't spawn and disconnect after 10 sec

### ISSUE THREAD

**Issue by receptor94** [openmultiplayer/server-beta-old#184]
# Description

The NPCs connect to the server, but do not spawn and disconnect automatically after 10 seconds. 
The same code perfectly works with 0.3.7 SAMP server.

# How to re-produce this bug

*Tell us a how to re-produce this bug in steps for example:*

1. ConnectNPC("Exmple_name","example");
2. Check the logs
3. Check the client

# Relevant log output

Check the video: https://drive.google.com/file/d/1kXryAqqrA9lyMQ2lTn8TgcrfrC18WcMw/view?usp=sharing

# open.mp server version

build9

# Operating system or distribution

Win 10 latest release

# Contact information

Discord: Jazi#8186

# Additional information

n/a

**Comment by AmyrAhmady** [comment]
Please provide a minimal script so we can test it and reproduce this bug
Create a new issue if you're still having it
