### ISSUE TITLE
[BUG]: Syncing trailers outside the stream zone

### ISSUE THREAD

**Issue by m1ronzy** [openmultiplayer/server-beta-old#185]
# Description

Trailers detach, change their position when the player leaves the stream zone and returns to it
Check the video: https://youtu.be/Zl_JF_mdHCk

# open.mp server version

build9

# Operating system or distribution

Windows 10 / Linux (Debian 10.12)

# Contact information

M1RoN#6464

**Comment by ksenonadv** [comment]
Fixed next build.
