### ISSUE TITLE
[BUG]: Build 9 maintheard stop working after player join the server with 0.3 DL feature enabled

### ISSUE THREAD

**Issue by Abyss-z94** [openmultiplayer/server-beta-old#187]
# Description
I run the server with my gamemode using these plugin (crashdetect streamer mysql ColAndreas sscanf whirlpool GPS discord-connector PawnPlus, Pawn.Raknet, Pawn.CMD) and enable artwork to test build 9 features with default _models_ folder that i took from 0.3 DL server files with default artconfig.txt also. 

_AddCharModel(305, 20001, "lvpdpc2.dff", "lvpdpc2.txd");
AddCharModel(305, 20002, "lapdpd2.dff", "lapdpd2.txd");
AddSimpleModel(-1,19379, -2000, "wallzzz.dff", "wallzzz.txd");_

When im connect the server with 0.3 DL client, it's does create cache and server ip folder but none of files are process to download, and after i quit the game, the server still show me as a online player, no left message from server console.

Even on bare gamemode and remove all of plugins config in server.cfg, the server just crashed after player connected the game.

I've posted my problem on omp-server-beta channel on open.mp discord cause i don't know what just happened to my server. Mike said the main thread from omp has stop working.

# How to re-produce this bug
https://youtu.be/tvKEXBCM-P8

# open.mp server version: build 9

# Operating system or distribution: window 10

*Tell us what operating system or distribution did you use when you did encounter this bug?*

# Contact information

*JJs#0020*

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by xunder-matth** [comment]
AFAIK Pawn.CMD and Pawn.RakNet must be recompiled to work with build 9.

**Comment by ksenonadv** [comment]
Not related to open.mp. Custom components need to be updated.
