### ISSUE TITLE
[BUG]: external access does not work

### ISSUE THREAD

**Issue by SantiagoBoss1** [openmultiplayer/server-beta-old#190]
The problem is that I opened the ports, configured the cfg everything was done correctly, I turn on the server, give the external ip to a friend and the IP does not work, I check it still does not work

**Comment by Hual** [comment]
post logs

**Comment by SantiagoBoss1** [comment]
[log.txt](https://github.com/openmultiplayer/server-beta/files/9532876/log.txt)

**Comment by AmyrAhmady** [comment]
Use samp with the same port, tell then if you are able to connect, this is more likely an issue from your side (as in your server's configuration) because anyone else is able to do it without any issue.

**Comment by SantiagoBoss1** [comment]
Окей
