### ISSUE TITLE
[BUG]: Client Get freezed in Download Screen (0.3.DL)

### ISSUE THREAD

**Issue by VictorMacielGhost** [openmultiplayer/server-beta-old#191]
# Description

I'm Using 0.3.DL Version, and after use gmx command to load more skins (1 more only) by OnGamemodeInit, i got stucked in the downloading screen with no models / textures to download

![image](https://user-images.githubusercontent.com/87531280/189457484-6a6e101d-eaf1-400d-bd7f-eb1c5770d3dd.png)

# How to re-produce this bug

1. Step One: Load the server with 1 (in my case was 2) models and textures in OnGamemodeInit, with the player connected, try:
2. Step Two: Add a new one (all via script in my case) in Gamemode Init
3. Use GMX (in my case was prompt gmx)

# Relevant log output

```
*None Relevant Log output*
```

# open.mp server version

0.3.DL Build 9 (windows)

# Operating system or distribution

Windows 10 Home Edition

# Contact information

*ex. Victor Ghost#9449 or vtbolado17@gmail.com*

# Additional information

After Quit the game and try enter again, 0.3.DL MP (client) won't load anymore (I Reinstalled both, gta and MP and didn't work, clear cache etc, but nothing, i got stuck in :
![image](https://user-images.githubusercontent.com/87531280/189457767-81c7b064-dce5-4d24-a933-0e74348dd37f.png)

**Comment by ksenonadv** [comment]
Fixed next build.
