### ISSUE TITLE
[BUG]: Assets aren't downloaded after GMX in DL

### ISSUE THREAD

**Issue by MeIsAlan** [openmultiplayer/server-beta-old#192]
# Description
NOTE: This issue was found when I was testing an another issue by Victor Ghost#9449 in discord, You can see his issue here: https://github.com/openmultiplayer/server-beta/issues/191
I'm encountering a bug after I restart the server using GMX(from in-game) with a DL model(skin), When I start the server properly, everything loads fine and all the models work but when I GMX, The server restarts and everything works fine BUT none of the models are downloaded.
NOTE: I get an error in game saying "Warning: SetPlayerSkin 20003 isn't a valid ped model."

# How to re-produce this bug

1. *Make a simple server using build 9 and add a AddCharModel to artconfig.txt* NOTE: Make sure to enable artwork in server.cfg using 'useartwork 1'
2. *Run the server and go in-game*
3. *Get in game, Set your skin to the one you downloaded, Login with rcon, And /rcon GMX*

# Relevant log output

My log output dosen't say much as when I restart the server using GMX for some reason, This is litteraly all it says after I restart:
 [01:05:28] [Info] AMX (179578180) loaded
[01:05:28] [Info]  
[01:05:28] [Info]  
[01:05:28] [Info]  
[01:05:28] [Info]  ======================================= 
[01:05:28] [Info]  |                                     | 
[01:05:28] [Info]  |        YSI version 3.09.0684        | 
[01:05:28] [Info]  |        By Alex "Y_Less" Cole        | 
[01:05:28] [Info]  |                                     | 
[01:05:28] [Info]  ======================================= 
[01:05:28] [Info]  

# open.mp server version

Build 9

# Operating system or distribution

Debian 10

# Contact information

Discord tag: Alan!#8303

# Additional information

I've discussed this is in the SA:MP discord with someone who had a similar issue to this, But in his case, The client would crash after he restarts the server using GMX, He already started an issue, You can see the discord the whole conversation in discord here: https://discord.com/channels/231799104731217931/231799180127895553/1017925458295279677

**Comment by ksenonadv** [comment]
Fixed next build.
