### ISSUE TITLE
[BUG]: Skin bugged and character flying

### ISSUE THREAD

**Issue by AthallahDzaki** [openmultiplayer/server-beta-old#193]
# Description

Player skin bugged and game unplayable with flying character

# How to re-produce this bug

I'm sorry, i don't know how to reproduce this bug with source code.
[VID](https://youtu.be/00Aqpb6CTOY)

# Relevant log output

~

# open.mp server version

Build 9

# Operating system or distribution

Windows 10

# Contact information

ANGGA#2225

# Additional information

Only Happend at Build 9, Build 8 this bug not happend

**Comment by AmyrAhmady** [comment]
Can you try build 10 and report it back?

**Comment by AthallahDzaki** [comment]
Fixed with Reseting player Camera Before Spawning.
