### ISSUE TITLE
[BUG]: spawning in pickups outside of the gtasa map (±4096.0)

### ISSUE THREAD

**Issue by realdiegopoptart** [openmultiplayer/server-beta-old#196]
# Description

try spawning in a Pickup outside of the gtasa map (±4096.0)

# How to re-produce this bug

spawn a pickup outside of the gtasa map

# open.mp server version

*What open.mp server version are you using?

bug appears on SA:MP, chances are high it appears in opem.mp

# Contact information

realdiegopoptart#2998 (discord)

**Comment by AmyrAhmady** [comment]
it's a limitation from the game itself, not possible to fix without a client
