### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: GetNetworkStats small difference

### ISSUE THREAD

**Issue by omcho420** [openmultiplayer/server-beta-old#198]
# Description

Basically there is a missing space in the first row

# How to re-produce this behavior difference

1. Just do this:
new stats[400+1];
GetNetworkStats(stats, sizeof(stats)); // get the servers networkstats
ShowPlayerDialog(playerid, 0, DIALOG_STYLE_MSGBOX, "Server Network Stats", stats, "Close", "");

3. Output is:
Server Ticks:200
Messages in Send buffer: 0

4. Instead of
Server Ticks: 200
Messages in Send buffer: 0

# Relevant log output

```
*Paste your relevant log output here!*
```

# open.mp server version

build10

# Operating system or distribution

Linux

# Contact information

omcho#7942

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by omcho420** [comment]
I know this is not a big difference or anything I just noticed it somehow 😓

**Comment by ksenonadv** [comment]
Fixed next build.
