### ISSUE TITLE
[BUG]: One more problem with displaying cyrillic chars in console

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#199]
# Description

Starting from build 10 (but working ok on build 9) another problem appeared with cyrillic chars displaying in the line `Loaded <n> component(s) from <path>`. If the path has any ru letters, this will be shown as some unreadable mojibake.

# How to re-produce this bug

Put the omp server package into some folder that contains non-latin chars.

# Relevant log output

**Build 10:**

![image](https://user-images.githubusercontent.com/13169094/189522315-8e8befce-2404-462e-b3d4-0a2c58774ae1.png)

**Build 9:**

![image](https://user-images.githubusercontent.com/13169094/189522333-d1e47d42-3cfa-48cc-9c2a-cf6c765094cd.png)

# open.mp server version

[Build 10](https://github.com/openmultiplayer/server-beta/releases/tag/build10)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by AmyrAhmady** [comment]
Fixed in next build
