### ISSUE TITLE
[BUG]: Expection in SHA256_PassHash: "bad variant access"

### ISSUE THREAD

**Issue by criticalerror99** [openmultiplayer/server-beta-old#2]
# Description

*SHA256_PassHash returns "bad variant access" expection when I'm hashing already hashed password (by Whirlpool).*

# How to re-produce this bug

```
new inputhash[512];
WP_Hash(inputhash, 512, inputtext);
SHA256_PassHash(inputhash, SALT, inputhash, 512);
```

# Relevant log output

```
(20.04 21:31:19) [Warning] Using unsafe hashing function SHA256_PassHash
(20.04 21:31:19) [Info] [PAWN-LOG] ERROR: Exception in SHA256_PassHash: "bad variant access"
```

# open.mp server version

*public beta build 1*

# Operating system or distribution

*Microsoft Windows 11 64-bit*

# Contact information

*critical#0937*

**Comment by ksenonadv** [comment]
Fixed next build.
