### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Problems with including sscanf

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/server-beta-old#200]
# Description

Working on Build 8 with a Blank Script with compiler 3.10.10. Only a mysql reg/log system is working.
if i include sscanf 2.13.2 i become these lines from server
crashdetect give some lines. without sscanf all clear.

# How to re-produce this behavior difference

I dont know its relevant, because thats on build 8, but
nobody could help me with it, should report it as an error

# Relevant log output

![Unbenannt](https://user-images.githubusercontent.com/108746459/189523462-352d985b-fdee-4459-b55a-72fb5daee55d.png)

![Unbenannt2](https://user-images.githubusercontent.com/108746459/189523467-f5bedd5f-7b27-4d65-b974-c0d26de44620.png)

# open.mp server version

Build 8

# operating system

Windows 11 Pro 21H2

# Contact information

NoxiZ#6965

# Additional information

@Y-Less

**Comment by NexiusTailer** [comment]
(Build 10 is the latest one now)

**Comment by Y-Less** [comment]
Does the code work on SA:MP?

**Comment by ghost** [comment]
Working perfectly on SA-MP.
i have upgraded to Build 10, same error

**Comment by Zorono** [comment]
@NoxiZ95 

> Working perfectly on SA-MP. i have upgraded to Build 10, same error

try @Y-Less 's version ?? https://github.com/Y-Less/sscanf/releases/tag/v2.13.2

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
hey, found out that the error is triggered by my script. If it's relevant, I'll send the script.
If not, I think this can be closed
