### ISSUE TITLE
[BUG]: SetTimerEx

### ISSUE THREAD

**Issue by m1ronzy** [openmultiplayer/server-beta-old#202]
# Description

If you specify the interval value 0, the server freezes

# How to re-produce this bug

SetTimerEx("TestTimer", 0, false, "d", playerid);

# open.mp server version

build10

# Operating system or distribution

windows / linux (debian 10.12)

# Contact information

M1RoN#6464

**Comment by morozovxc** [comment]
And what are 0s timers for?

**Comment by Y-Less** [comment]
I think we need a bit more code, like what the timer is calling.  A few of us use 0ms timers all the time and haven't seen this.

> And what are 0s timers for?

They call code as soon as possible after the current callback ends.

**Comment by AmyrAhmady** [comment]
Are you able to provide a simple working script for us to test this and reproduce this bug?

**Comment by m1ronzy** [comment]
Now I tried to reproduce the error on an empty script - it did not work. I looked into the code of the main script and found an error there. Sorry, false alarm.
