### ISSUE TITLE
[BUG]: Server will crash if an invalid model folder is provided

### ISSUE THREAD

**Issue by TommyB123** [openmultiplayer/server-beta-old#203]
# Description

If you specify an invalid folder to load models from, the server will crash/hang upon attempting to read any files from it. This maty not happen if you're using `artconfig.txt` to load files, but if you have model loading calls integrated in your source code, you're going to crash.

# How to re-produce this bug

Change `models_path` in `config.json` to an invalid directory.

# Relevant log output

N/A

# open.mp server version

Beta 9

# Operating system or distribution

Windows 11

# Contact information

no

# Additional information

no

**Comment by MeIsAlan** [comment]
Why? Just, Why?

**Comment by ksenonadv** [comment]
Fixed next build.
