### ISSUE TITLE
[BUG]: String formatting error should tell you what the string is

### ISSUE THREAD

**Issue by TommyB123** [openmultiplayer/server-beta-old#204]
# Description

If you format a string with more parameters than specifiers, you'll get a warning in the server console. However, you are not told what string is related to the error, so locating the offending format call is rather difficult. This warning should tell you what the string in question contains.

# How to re-produce this bug

N/A

# Relevant log output

```
[Error] String formatted incorrectly - parameter 4 (total 3)
```

# open.mp server version

Beta 9

# Operating system or distribution

Windows 11

# Contact information

no

# Additional information

no

**Comment by AmyrAhmady** [comment]
Fixed next build
