### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Trailer

### ISSUE THREAD

**Issue by kaykessantos** [openmultiplayer/server-beta-old#205]
# Description

Well, when a trailer is attached to the trailer and then the truck respawns (respawn_delay) the trailer doesn't respawn, it's still there.

# How to re-produce this behavior difference

1. Attach a trailer to the truck (through the game)
2. Move it, take it out of the birth position
3. Wait for the respawn_delay time to pass and the truck will respawn and the trailer will not

# open.mp server version

[open.mp server public beta build 10 (hotfix)](https://github.com/openmultiplayer/server-beta/releases/tag/build10)

# Operating system or distribution

Windows Server 2019 Datacenter Evaluation (v1809)

# Contact information

Kayke#1533

**Comment by HenriqueSilv4** [comment]
**UPDATE** 

Here is the behavior in Open-MP beta build 10
https://youtu.be/AMwpl8af-NM

How it work on SA-MP
https://youtu.be/ZkodshJO5Mw

I'm using SampSharp and Open-MP beta build 10.
It will happen with CreateVehicle and StaticVehicle. 

Trailer will not trigger OnVehicleDeath :
`protected override void OnVehicleDied(BaseVehicle vehicle, PlayerEventArgs e)
        {
            base.OnVehicleDied(vehicle, e);
            vehicle.Respawn();
        }`

Trailer will not respawn after respawn delay

`player.JobSecondaryVehicle = BaseVehicle.CreateStatic(VehicleModelType.ArticleTrailer, SpawnPos, Angle, -1, -1, 10, false);`

OR

`player.JobSecondaryVehicle = BaseVehicle.Create(VehicleModelType.ArticleTrailer, SpawnPos, Angle, -1, -1, 10, false);`

**Comment by ksenonadv** [comment]
Fixed next build.
