### ISSUE TITLE
[BUG]: GameModeExit() is not called

### ISSUE THREAD

**Issue by L0K3D** [openmultiplayer/server-beta-old#21]
# Description

When you call GameModeExit() nothing happens

# Without open-mp

![without](https://user-images.githubusercontent.com/73894829/164446141-09cd2932-d06b-4743-980f-302cacb5e330.png)

# With open-mp
![with openmp](https://user-images.githubusercontent.com/73894829/164446314-2198568c-058c-4bdc-aee0-f9dbb5fcdb96.PNG)

**Comment by ksenonadv** [comment]
Fixed next build.
