### ISSUE TITLE
[BUG]: TogglePlayerGhostMode Desync

### ISSUE THREAD

**Issue by Marevin** [openmultiplayer/server-beta-old#210]
# Description

Some examples of a player with TogglePlayerGhostMode set to true having animation desyncs.

# How to re-produce this bug

While the player has TogglePlayerGhostMode(playerid, true), shown examples are:
- Aiming while falling from a height
- Shooting while falling from a height
- Falling onto the ground and teleporting (SetPlayerPos)

# Relevant log output

n/a

# open.mp server version

windows server, public beta 10

# Operating system or distribution

Win10 Home

# Contact information

@Marevin

# Additional information

Here's a video demonstration
https://www.youtube.com/watch?v=Eb1U4mWyjrU
First showing how the sync is fine until the player does /ghost which basically toggles ghostmode 
and attaches a text3d for the purpose of this demonstation.

Toggling GhostMode off at runtime fixes the player sync, no need for respawns or streaming the player out and in, 
although it fixes the "fallen down" stuck animation situation.

Side note:
I spoke about desync issues with open.mp on sa-mp discord, believing to be behavior differences (from beta 7) to sa-mp but apparently it's related to this new function.

**Comment by ksenonadv** [comment]
The function itself is a "hack". 
We cannot fix this bug without a client.
