### ISSUE TITLE
[BUG]: StartRecordingPlayerData (Don't work)

### ISSUE THREAD

**Issue by morozovxc** [openmultiplayer/server-beta-old#215]
# Description
### - I can't record a replay to a player

# How to re-produce this bug
### - See the screenshot
![image](https://user-images.githubusercontent.com/98089803/195672043-a6a1e0e1-0755-418f-8e17-366590073ada.png)

# Relevant log output

```
[PAWN-LOG] ERROR: Exception in StartRecordingPlayerData: "Pawn native not yet implemented."
[PAWN-LOG] ERROR: Exception in StopRecordingPlayerData: "Pawn native not yet implemented."
```

# open.mp server version (Build 10)
# Operating system or distribution
###  Windows 11 21H2 build 22000.856
# Contact information
morozovxc#0533
xbolotovnikita@gmail.com

**Comment by AmyrAhmady** [comment]
They are not implemented since they are marked as legacy and probably will never be (in favor of having an FCNPC-like system), they're already in our list but low priority
