### ISSUE TITLE
[BUG]: No error message when samp-npc.exe not found

### ISSUE THREAD

**Issue by LDami** [openmultiplayer/server-beta-old#217]
# Description

The open.mp server does not show error message when the samp-npc executable is not found.

# How to re-produce this bug

1. Create your npcmode script (with the .rec file in npcmodes/recordings)
2. Call ConnectNpc("npcname", "npcscript")
3. Check that samp-npc.exe is not present in the open.mp folder (which is the case in the release builds)

# Relevant log output

# open.mp server version

0.0.10.2126 commit 28309b34dc7a8102058bccd6bc9660d7aa71a9b8

For a development build please specify its commit hash.*

# Operating system or distribution

Windows 10

# Contact information

LDami#8585

# Additional information

**Comment by Hual** [comment]
Fixed in the next build
