### ISSUE TITLE
[BUG]: SetPlayerName bug

### ISSUE THREAD

**Issue by Drown14** [openmultiplayer/server-beta-old#221]
# Description

*When i used SetPlayerName(playerid,"Ghost"); function i got a new message on console: sscanf error: System not initialised. My sscanf plugin the most freshed.*

# How to re-produce this bug

*be used SetPlayerName function and be can see the console this error and scoreboard was not refreshed.*

# Relevant log output

```
*[Info] sscanf error: System not initialised.*
```

# open.mp server version

*0.3.7-R2*

**Comment by AmyrAhmady** [comment]
This is not open.mp's fault, please create an issue in sscanf repository
