### ISSUE TITLE
[BUG]: Model names

### ISSUE THREAD

**Issue by m1ronzy** [openmultiplayer/server-beta-old#223]
# Description

If you have different names when loading object models (for example: ocmiamistrip9x.txd in OnGameModeInit and ocmiamistrip9X.txd in the models folder), then you will get the following error in the logs:

[Error] [artwork:error] Cannot add custom model. ocmiamistrip9x.txd doesn't exist

The differences are in uppercase and lowercase letters, which is why these files are not loaded when loading the game mod. This error is missing on windows build.

# open.mp server version

build10

# Operating system or distribution

Linux (debian10)

# Contact information

M1RoN#6464

**Comment by Alasnkz** [comment]
Windows does not care about case sensitivity (unless explicitly told so), Linux does, that's just how Windows & Linux has worked for years. Just be careful, not a bug.
