### ISSUE TITLE
[BUG]: Cannot run omp-server arm build on a raspberry pi 3b+

### ISSUE THREAD

**Issue by vico93** [openmultiplayer/server-beta-old#226]
# Description

I downloaded `open.mp-linux-arm.tar.xz` from the build 10 to my Pi 3b+ using `wget`, extracted it with `tar -xf ` and when i tried to run `omp-server` it gives me the message `-bash: omp-server: command not found`

What i'm doing wrong?

# open.mp server version

*[open.mp server public beta build 10 (hotfix)](https://github.com/openmultiplayer/server-beta/releases/tag/build10)*

# Operating system or distribution

Raspberry Pi OS Lite (based on Debian buster).
From `cat /etc/os-release`:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
From `uname -a`:
`Linux <pi-name> 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux`

**Comment by AmyrAhmady** [comment]
Use `ls` see if files are even there first, then try doing `./omp-server` 

Edit: And please, issue template has other fields to fill like contact info, would have been nice to contact you on discord to solve it in real time

**Comment by Hual** [comment]
You probably need to install the armhf (32-bit) libraries for your distro

**Comment by vico93** [comment]
> You probably need to install the armhf (32-bit) libraries for your distro

How can I do that?

**Comment by Disinterpreter** [comment]
> > You probably need to install the armhf (32-bit) libraries for your distro
> 
> How can I do that?

Or chroot armhf OS and start the server there.

**Comment by vico93** [comment]
I resolved installing the 32-bit armhf libraries as Hual instructed. BTW why build 11 doesnt have an arm build?

**Comment by AmyrAhmady** [comment]
Seems like your issue is fixed, build 11 didn't come with an ARM build since our ARM CI runner is not available anymore, you will be able to build the project yourself when it's open source

**Comment by Disinterpreter** [comment]
> ARM CI runner is not available anymore

Just build it manually and put to the release, or use crosscompile.

**Comment by AmyrAhmady** [comment]
We do not have an ARM device to do it, that's why
and it's not in our priority list to care about it right now

**Comment by vico93** [comment]
> Seems like your issue is fixed, build 11 didn't come with an ARM build since our ARM CI runner is not available anymore, you will be able to build the project yourself when it's open source

That's sad. The major reason i'm using Open.MP over stock SA:MP is because it had an ARM build that allowed me to run the server on my Raspberry Pi.

**Comment by AmyrAhmady** [comment]
Which you can wait for public release and this project going open source, and either you or community builds it for ARM

**Comment by Disinterpreter** [comment]
> We do not have an ARM device to do it, that's why and it's not in our priority list to care about it right now

why you need ARM device to compile that?

**Comment by AmyrAhmady** [comment]
> why you need ARM device to compile that?

Then how are we gonna build it for ARM? I'm not experienced with it so please tell me

Edit: (without using qemu, it's painfully slow for our case)

**Comment by Disinterpreter** [comment]
> > why you need ARM device to compile that?
> 
> Then how are we gonna build it for ARM? I'm not experienced with it so please tell me
> 
> Edit: (without using qemu, it's painfully slow for our case)

are you kidding me? Just build with `gcc-arm-linux-gnueabihf`, and if you don't want to test, add to the file name `$name-unstable` ppl will come all bugs if they need that.

Also works for [clang](https://clang.llvm.org/docs/CrossCompilation.html), but I'm not test that. Just I read about that.

**Comment by AmyrAhmady** [comment]
And again, there's something else with higher priority, if you just wait, you'll understand. If there's any further discussion please move it to discord.

Note: you can't use gcc with open.mp project, it's clang only, and we use conan dependency management

**Comment by AGraber** [comment]
@Disinterpreter 
I started looking into cross-compiling (without virtual machine stuff, I don't know why that was being done in the first place)

Unfortunately conan has poor support for clang. The only mechanism it seems to support is by setting the compilers like you said, but clang doesn't have that (clang is a single executable that can already compile for everything, unlike gcc where each compiler is a different executable). Because of this conan generates code for x86.

Check out this issue: https://github.com/conan-io/conan/issues/7868

We can either try to overcome this by somehow forcing clang to only build for a specific architecture, or we can support gcc. I would like to keep using clang because code generation is generally better.

**Comment by Disinterpreter** [comment]
> We can either try to overcome this by somehow forcing clang to only build for a specific architecture, or we can support gcc. I would like to keep using clang because code generation is generally better.

As you wish (at least I'm not a maintainer, so it isn't my decision), but pay attention, the quantity of ARM users will increase year by year.

But I suggest make another issue about this trouble and do not close it. Kinda a FAQ instruction why you are can't do that right now.

(my IMO, i don't believe that it will be open source, so I don't believe that I can build it in future)

**Comment by AmyrAhmady** [comment]
Like I said, it is in our minds, just not highest priority yet
We will make another issue in main repository when open source.
and regarding your last line, let time decide :)
