### ISSUE TITLE
[BUG]: StartRecordingPlayerData and StopRecordingPlayerData doesn't work on Open.MP build 10

### ISSUE THREAD

**Issue by vico93** [openmultiplayer/server-beta-old#228]
# Description

I tried to make a test gamemode to record NPCs, but when i tried to start a recording in-game (that calls `StartRecordingPlayerData`) i got the following lines on my log:

```
[22:18:34] [Info] [PAWN-LOG] ERROR: Exception in StartRecordingPlayerData: "Pawn native not yet implemented."
[22:18:43] [Info] [PAWN-LOG] ERROR: Exception in StopRecordingPlayerData: "Pawn native not yet implemented."
```

# How to re-produce this bug

1. *Compile and add [this gamemode](https://github.com/vico93/o_feudo/blob/default/npc_recorder/gamemodes/of_npc_recorder.pwn) to a test omp build 10 server*
2. *Login as admin via RCON;*
3. *Spawn a vehicle (with `/v <model id>`, or one of the named commands like `/bus` or `/camper`);*
4. *Define a recording filename with `/setscriptname <filename without .rec>` *;
5. *Press Y (the key to say 'yes' on singleplayer) to start a recording session, and N (key to 'no' in SSP) to stop the recording*;
6. *Console should show lines similar to the ones above when StartRecordingPlayerData and StopRecordingPlayerData are tried to be called*.

# open.mp server version

*[open.mp server public beta build 10 (hotfix)](https://github.com/openmultiplayer/server-beta/releases/tag/build10)*

# Operating system or distribution

*Windows 10 x64*

# Contact information

*vico#9414 on Discord. I'm a member of the Open.MP/SA:MP server*

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by AmyrAhmady** [comment]
recording natives are not implemented in open.mp and there's no plan in adding them yet either
