### ISSUE TITLE
symbol already defined:

### ISSUE THREAD

**Issue by 03815** [openmultiplayer/server-beta-old#229]
On SA-MP 0.3.7-R2

\pawno\include\omp.inc(40) : error 021: symbol already defined: "AllowPlayerTeleport"
\pawno\include\omp.inc(277) : error 021: symbol already defined: "AllowAdminTeleport"
\pawno\include\omp.inc(279) : error 021: symbol already defined: "AllowInteriorWeapons"

**Comment by AmyrAhmady** [comment]
Use latest omp.inc, if issue persists create another issue please but use a proper issue template this time
https://github.com/openmultiplayer/server-beta/blob/master/omp.inc
