### ISSUE TITLE
[BUG]: OnPlayerWeaponShot Doesn't Work

### ISSUE THREAD

**Issue by nexquery** [openmultiplayer/server-beta-old#23]
# Description

The OnPlayerWeaponShot callback does not work if you fire a weapon at an object created with CreateDynamicObject.
If you fire a weapon at an object created with CreateObject, the OnPlayerWeaponShot callback runs.

[OnPlayerWeaponShot - CreateObject](https://www.youtube.com/watch?v=vftZoYcTk1o)
[OnPlayerWeaponShot - CreateDynamicObject](https://www.youtube.com/watch?v=VvEcBwQUYYk)

# How to re-produce this bug
```c
#include <a_samp>
#include <streamer>
#include <zcmd>

public OnGameModeInit()
{
    CreateDynamicObject(18850, 564.14252, -2687.29346, 2.39084, 0.00000, 0.00000, 0.00000);
    //CreateObject(18850, 564.14252, -2687.29346, 2.39084, 0.00000, 0.00000, 0.00000);
    return 1;
}

main()
{
    
}

CMD:goto(playerid, params[])
{
    SetPlayerPos(playerid, 564.14252, -2687.29346, 2.39084 + 20.0);
    return 1;
}

CMD:weapon(playerid, params[])
{
    GivePlayerWeapon(playerid, 31, 500);
    return 1;
}

public OnPlayerWeaponShot(playerid, weaponid, hittype, hitid, Float:fX, Float:fY, Float:fZ)
{
    new sz[50];
    format(sz, sizeof(sz), "Weapon ID: %d, Ammo: %d", weaponid, GetPlayerAmmo(playerid));
    SendClientMessage(playerid, -1, sz);
    printf(sz);
    return 1;
}
```

# Relevant log output

```
-------------------------------------------------
CreateObject:

[16:34:26] [Info] Weapon ID: 31, Ammo: 500
[16:34:26] [Info] Weapon ID: 31, Ammo: 499
[16:34:27] [Info] Weapon ID: 31, Ammo: 498
[16:34:28] [Info] Weapon ID: 31, Ammo: 497

-------------------------------------------------
CreateDynamicObject:
```

# open.mp server version

[open.mp server public beta build 1 ](https://github.com/openmultiplayer/server-beta/releases/tag/build1)

# Operating system or distribution

Windows 10 Home

# Contact information

Nexor#4730

# Additional information
N/A

**Comment by ksenonadv** [comment]
That's not an open.mp bug.

**Comment by xunder-matth** [comment]
Use [OnPlayerShootDynamicObject](https://github.com/samp-incognito/samp-streamer-plugin/blob/5696cee2d0becaeed7f6d99d8525ffeb664a88b3/streamer.inc#L443).
