### ISSUE TITLE
[New Feature]: "• Report warnings when trying to register an already registered native name"

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/server-beta-old#231]
## Server version
**[open.mp 0.0.11.2331](https://github.com/openmultiplayer/server-beta/releases/tag/build11)**

## Operating system or distribution
**Windows 10 & 11**

## Relevant log output
![Screenshot_2](https://user-images.githubusercontent.com/61196324/209480084-4de67458-b662-426d-b62b-8ae5ee2c6af3.png)

**Comment by AmyrAhmady** [comment]
you are loading sscanf twice, once as a plugin and once as a component
