### ISSUE TITLE
[Enhancement]: Set in-game clock timescale

### ISSUE THREAD

**Issue by vico93** [openmultiplayer/server-beta-old#233]
# Description

According to [some GTA SA save editors](https://www.mixmods.com.br/2013/11/gta-sa-savegame-editor-3-2/), is theoretically possible, in singleplayer, to change the length of in-game minutes to an arbitrary value in miliseconds - and also even the day of the week.

![image](https://user-images.githubusercontent.com/3485505/209597032-48a7afa3-8121-4ebf-8d9e-4eef75a5ba7b.png)

I'm wondering if would be possible to replicate such option in Open.MP server as well.

I know that is totally possible to disable the in-game clock for all players (`TogglePlayerClock`) and implement a parallel timekeeping system with the current tools we have, but we lose details like weather interpolation (when setting via `SetWeather`/`SetPlayerWeather`) and details of buildings that appears open during day and closed at night (maybe day of week can influence this latter aspect as well).

# Contact information

vico#9414 on Discord

**Comment by AmyrAhmady** [comment]
requires a client, please keep it server only for now
