### ISSUE TITLE
[Enhancement]: Customization of CJ (skin id 0)

### ISSUE THREAD

**Issue by vico93** [openmultiplayer/server-beta-old#234]
Currently, SA:MP/Open.MP only allows the default variation (clothing / body type) of CJ to be declared in either `AddPlayerClass(Ex)` or `SetPlayerSkin` (specifying ID 0 for it).

I propose or tweaking both functions or creating two counterparts of each (for me the most clean way to implement) that allows scripts to specify details like clothing, muscle, fat, tatoos and other body details of CJ.

Return values for these functions could reflect success or failure (0/1) and maybe a separate value in case of direct attempt to "manipulate" a skin that isn't CJ (-1?).

I don't see the need to tweak the class menu to account for changes to CJ skin specifically (too much hurdles and would need to be implemented in client as well), just the ability for server owners to specify CJ with specific details would be sufficient.

**Comment by AmyrAhmady** [comment]
requires a client, please keep it server only for now
