### ISSUE TITLE
[BUG]: Cannot run omp-server

### ISSUE THREAD

**Issue by m1ronzy** [openmultiplayer/server-beta-old#236]
# Description

Starting open.mp server (0.0.11.2331) from commit afa5cf8b85088f866972ee34ee7b75bfe80fc022
Loading component Pickups.so
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

This happens when the server starts, regardless of the script. This is the first component, it does not load and the server does not start.
Using this build: https://github.com/openmultiplayer/server-beta/releases/download/build11/open.mp-linux-x86.tar.gz

# open.mp server version

build11

# Operating system or distribution

debian10

# Contact information

M1RoN#6464

**Comment by AmyrAhmady** [comment]
Fixed in next build
