### ISSUE TITLE
[BUG]: omp-server won't load legacy plugins without adding `.so` extension

### ISSUE THREAD

**Issue by ohmypxl** [openmultiplayer/server-beta-old#241]
# Description

Y_Less said this in the discord:
> You shouldn't need `.so` on open.mp

Which he implies that you dont have to put `.so` in `config.json`, but when you do that it won't work, the plugins didn't load.

# How to re-produce this bug

* Download any legacy plugin out there
* Put it in `plugins/` folder
* Add your plugin name in `"legacy_plugins"` section without `.so` extension
* Run the server

# Relevant log output

```
[Fri, Dec 30, 2022 22:22 PM] [Info] Loading plugin: crashdetect
[Fri, Dec 30, 2022 22:22 PM] [Info] This file is not a SA-MP plugin.
[Fri, Dec 30, 2022 22:22 PM] [Info] Loading plugin: PawnPlus
[Fri, Dec 30, 2022 22:22 PM] [Info] This file is not a SA-MP plugin.
```

# open.mp server version

[beta 11](https://github.com/openmultiplayer/server-beta/releases/tag/build11)

# Operating system or distribution

Void Linux

# Contact information

Gotoh Aiura#8244

# Additional information

There should be no requirements for you to put any extensions in `legacy_plugins`, since it was supposed to detect which extension is appropriate for the operating system instead of letting user doing it manually like SA:MP does.

**Comment by Y-Less** [comment]
Thanks.  Fixed already.
