### ISSUE TITLE
[BUG]: Config options don't reset well.

### ISSUE THREAD

**Issue by Y-Less** [openmultiplayer/server-beta-old#242]
# Description

If the config has `game.use_manual_engine_and_lights: false` and a mode calls `ManualVehicleEngineAndLights()` that will set the setting to `true` and never reset it on GMX.  The ideal would be to go back to the setting from the config file rather than a generic default.

# How to re-produce this bug

*Tell us a how to re-produce this bug in steps for example:*

1. Set a config option.
2. Change it in a gamemode.
3. Load a different mode.

# Relevant log output

```
*Paste your relevant log output here!*
```

# open.mp server version

*What open.mp server version are you using?

For a development build please specify its commit hash.*

# Operating system or distribution

*Tell us what operating system or distribution did you use when you did encounter this bug?*

# Contact information

*ex. Username#1234 or email@example.com*

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by AmyrAhmady** [comment]
Fixed
