### ISSUE TITLE
[BUG]: hostname set by SendRconCommand not displaying in TAB and chat message (Connected to xyz)

### ISSUE THREAD

**Issue by criticalerror99** [openmultiplayer/server-beta-old#26]
# Description

*If you set hostname through **SendRconCommand**, tablist and chat information still uses hostname from server.cfg.*

# How to re-produce this bug

*Set any hostname through **SendRconCommand("hostname xyz");***

# Relevant log output

**server.cfg value**
![image](https://user-images.githubusercontent.com/22982995/164548416-7f86c2d6-164d-481f-a9f0-fc28438e6920.png)

**set hostname through SendRconCommand**
![image](https://user-images.githubusercontent.com/22982995/164548311-516cd987-f308-46de-b50e-e40bad8f46ca.png)

**hostname set by SendRconCommand on servers list**
![image](https://user-images.githubusercontent.com/22982995/164548357-042c78f6-cdf9-44b8-af5c-637026151552.png)

**in-game message with hostname from server.cfg**
![image](https://user-images.githubusercontent.com/22982995/164548375-1de253bd-9692-4a51-a122-cabd2800052d.png)

**tablist**
![image](https://user-images.githubusercontent.com/22982995/164548601-92301bad-1669-462d-96fb-659722c7826b.png)

# open.mp server version

*public beta build 2*

# Operating system or distribution

*Microsoft Windows 11 64-bit*

# Contact information

*critical#0937*

**Comment by ksenonadv** [comment]
Fixed.
