### ISSUE TITLE
[BUG]: InterpolateCamera

### ISSUE THREAD

**Issue by a-jeez** [openmultiplayer/server-beta-old#28]
# Description
If a player uses the InterpolateCamera while connecting into server, sometimes the camera position not working correctly.

# How to re-produce this bug

```
public OnPlayerConnect(playerid)
{
	TogglePlayerSpectating(playerid, true);
	SetPlayerInterior(playerid, 0);
	SetPlayerWeather(playerid, 1);
	InterpolateCameraPos(playerid, 2067.9924,-1806.3177,16.1916,2067.9924,-1806.3177,16.1916, 20000);
	InterpolateCameraLookAt(playerid, 2067.9924,-1806.3177,16.1916,2067.9924,-1806.3177,16.1916, 20000);
	return 1;
}
```
# Relevant log output

```
N/A
```

# open.mp server version
 open.mp server public beta build 1

# Operating system or distribution
Windows 10 Home

# Contact information

Phoenixx#2782

# Additional information

![samp_21_04_2022_20_36_26](https://user-images.githubusercontent.com/79042077/164562826-3ef84107-9cd8-4316-84b2-2f60c0c650c6.png)

**Comment by ksenonadv** [comment]
Please try to use build2.

**Comment by a-jeez** [comment]
Thanks, camera position is working properly in build2
