### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Fliterscript failed to load due to an console error displayed

### ISSUE THREAD

**Issue by Gothon369** [openmultiplayer/server-beta-old#29]
# Relevant log output

```
[Info] Could not find:

         vspawner.amx
                                While attempting to load a PAWN gamemode, a file-not-found error was
                                encountered.  This could be caused by many things:

                                * The wrong filename was given.
                                * The wrong gamemodes path was given.
                                * The server was launched from a different directory, making relative paths relative to the wrong place (and thus wrong).
                                * You didn't copy the file to the correct directory or server.
                                * The compilation failed, leading to no output file.
                                * `-l` or `-a` were used to compile, which output intermediate steps for inspecting, rather than a full script.
                                * Anything else, really just check the file is at the path given.
```

# open.mp server version

open.mp server public beta build 2

# Windows 10 Pro 21H2

# Contact information

 S.A.L.E.G.A.X.Y#7936

# Rejects loading filterscripts from .dir\filterscripts mainly vspawner
```
"pawn": {
        "legacy_plugins": [],
        "main_scripts": [
            "showcase"
        ],
        "side_scripts": [ < from this array witch i think its for loading filterscripts
            "vspawner" 
        ]
    },
```

*vspawner: in case i want to spawn a car and didnt made changes to the filterscript assuming i want to access command /vspawner and cannot login with /rcon login <somepassword> client\server is not aware of and send the "Bad password attempts may lead you to ban"

**Comment by AmyrAhmady** [comment]
if you are using config.json filterscript paths are relative to root directory, not whatever you have with old samp file structure
so for example if you want to load vspawner, you must put filterscripts/vspawner in side_scripts

**Comment by Gothon369** [comment]
that applies same for plugins?

**Comment by AmyrAhmady** [comment]
@Gothon369 No, legacy plugins, as the name can kinda give it away, are supposed to be compatible with samp-style plugins, so they must be in folder called `plugins`

This is kept because some plugins try to use relative paths for different purposes, like access upper level directory or anything else

**Comment by AmyrAhmady** [comment]
Closing this, if you think it's not supposed to be closed, create a new one or just post a comment here again
