### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Class selection skipped in Grand Larceny

### ISSUE THREAD

**Issue by Fairuz-Afdhal** [openmultiplayer/server-beta-old#3]
# Description

Class selection seems to be skipped entirely and it's selecting random class.

# How to re-produce this behavior difference

1. Run omp-server executable
2. Connect
3. Class selection is skipped

open.mp https://discord.com/channels/231799104731217931/966398440051445790/966420407890608178
sa-mp: https://discord.com/channels/231799104731217931/966398440051445790/966420436168605716

# open.mp server version

Beta build 1

# Operating system or distribution

Windows

# Contact information

Fairuz#4331

**Comment by mixedthoughts** [comment]
This is not only for grand lacerny.

If you use TogglePlayerSpectating(playerid,0) on playerconnect, after he registers or logins, you will get spawned immediately without class. This doesn't happen in samp. In samp you get access to the class selection.

**Comment by BeckzyBoi** [comment]
> This is not only for grand lacerny.
> 
> If you use TogglePlayerSpectating(playerid,0) on playerconnect, after he registers or logins, you will get spawned immediately without class. This doesn't happen in samp. In samp you get access to the class selection.

I'm using ForceClassSelection as a temporary fix. Hopefully this is fixed properly at some point, as of course it isn't possible to reverse the setting of ForceClassSelection without killing the player.

**Comment by AmyrAhmady** [comment]
Fixed in build 9
