### ISSUE TITLE
[BUG]: Characters don`t disappear after the server is restarting

### ISSUE THREAD

**Issue by L0K3D** [openmultiplayer/server-beta-old#31]
# Description

*Normally after the server is restarting players do not appear in the tab anymore or on the map until they are back into the game*

# How to re-produce this bug

*I think the video is enough to understand how to re-produce this bug*

# Video
https://www.youtube.com/watch?v=0SnF6J5sciU
# open.mp server version
*build 2*

**Comment by ksenonadv** [comment]
Fixed next build.
