### ISSUE TITLE
[BUG]: "Recreating" removed building is impossible

### ISSUE THREAD

**Issue by Zbyss** [openmultiplayer/server-beta-old#32]
# Description

As in title. Seems like `RemoveBuildingForPlayer` also removes the server-created object instead of only default SA objects.

# How to re-produce this bug

```pawn
public OnGameModeInit()
{
    CreateObject(8515, 2212.382812, 1083.210815, 7.873188, 0.000000, 0.000000, 0.000000);
    AddPlayerClass(0, 2151.73, 1002.4, 10.82, 0.0, 0, 0, 0, 0, 0, 0);

    return 1;
}

public OnPlayerConnect(playerid)
{
    RemoveBuildingForPlayer(playerid, 8515, 2212.3672, 1083.2266, 7.8750, 0.25);
    return 1;
}
```

# Relevant log output

N/A

# open.mp server version

open.mp server public beta build 2 

# Operating system or distribution

Microsoft Windows 11 64-bit

# Contact information

Zbyss.#2597

# Additional information

N/A

**Comment by ksenonadv** [comment]
Fixed next build.
