### ISSUE TITLE
[BUG]: strins wrong output

### ISSUE THREAD

**Issue by Zbyss** [openmultiplayer/server-beta-old#35]
# Description

See the example. Works fine if `pos` is used correctly (e.g. `strins(string, ".", 3)`), but I don't think this is the expected behaviour, especially if the code below runs properly on SA-MP server.

# How to re-produce this bug

```pawn
new string[8] = "123456";
print(string);
strins(string[3], ".", 0);
print(string);
```

# Relevant log output

SA-MP:
```
123456
123.456
```

open.mp:
```
123456
123
```

# open.mp server version

open.mp server public beta build 2

# Operating system or distribution

Microsoft Windows 11 64-bit

# Contact information

Zbyss.#2597

# Additional information

N/A

**Comment by ksenonadv** [comment]
Hello, there's a small difference between SA:MP strins and our implementation. 
SAMP strins is ignoring the maxlength parameter, which is prone to OOB. 
open.mp one doesn't. 


Due to some compiler bug/limitation wrong maxlength is pushed when you are using string[3] so you need to set it yourself.

```pawn
strins(string[3], ".", 0, sizeof string);
```
