### ISSUE TITLE
[BUG]: PutPlayerInVehicle resets camera

### ISSUE THREAD

**Issue by Zbyss** [openmultiplayer/server-beta-old#36]
# Description

`PutPlayerInVehicle` resets player camera even if we're putting the player into the same vehicle, as his current one.

# How to re-produce this bug

```pawn
public OnPlayerSpawn(playerid)
{
    PutPlayerInVehicle(playerid, CreateVehicle(400, 5.0, 0.0, 5.0, 0.0, -1, -1, -1), 0);
    InterpolateCameraPos(playerid, 20.0, 0.0, 10.0, 0.0, 20.0, 10.0, 10000, CAMERA_MOVE);
    SetTimerEx("Timer_PutPlayerInVehicle", 2500, 0, "i", playerid);
    return 1;
}

forward Timer_PutPlayerInVehicle(playerid);
public Timer_PutPlayerInVehicle(playerid)
{
    return PutPlayerInVehicle(playerid, GetPlayerVehicleID(playerid), 0);
}
```

# Relevant log output

N/A

# open.mp server version

open.mp server public beta build 2

# Operating system or distribution

Microsoft Windows 11 64-bit

# Contact information

Zbyss.#2597

# Additional information

N/A

**Comment by ksenonadv** [comment]
The game is changing the camera. 
All we can do right now is to stop sending the RPC if players is already in that vehicle and that seat.
