### ISSUE TITLE
[BUG]: SendDeathMessage/SendDeathMessageToPlayer bug

### ISSUE THREAD

**Issue by Sancky** [openmultiplayer/server-beta-old#39]
# Description

SendDeathMessage / SendDeathMessageToPlayer are not working on OnPlayerDisconnect.

# How to re-produce this bug

```
public OnPlayerDisconnect(playerid, reason) 
{
    SendDeathMessage(INVALID_PLAYER_ID, playerid, 201);
    return 1;
}
```

# Relevant log output

-

# open.mp server version

build 2

# Operating system or distribution

Windows 10 64-bit

# Contact information

Sancky#3199

# Additional information

-

**Comment by ksenonadv** [comment]
Fixed next build.
