### ISSUE TITLE
[BUG]: Delayed execution of timer functions is applied before the timer is called

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#41]
# Description

Sounds as strange as possible and I'll not describe my assumptions, just look at the order of calls in the logs and compare the behavior with samp server below.

# How to re-produce this bug

```pawn
#include <a_samp>

main(){}

public OnPlayerConnect(playerid)
{
	SetTimerEx("TestFunc", 200, 0, "i", playerid);
	print("Timer started in OnPlayerConnect event!");
	return 1;
}

forward TestFunc(playerid);
public TestFunc(playerid)
{
	TogglePlayerSpectating(playerid, 1);
	print("TogglePlayerSpectating is set to 1 by a timer!");
	return 1;
}

public OnPlayerStateChange(playerid, newstate, oldstate)
{
	if(newstate == PLAYER_STATE_SPECTATING)
	{
		printf("OnPlayerStateChange changed to PLAYER_STATE_SPECTATING");
	}
	return 1;
}
```

# Relevant log output

OMP server:
![image](https://user-images.githubusercontent.com/13169094/164895937-7742b5ad-899c-4a1a-ae47-26239b306d5a.png)

Here you see that applying of PLAYER_STATE_SPECTATING were BEFORE an actual calling of TogglePlayerSpectating in a timer.

Should be this (as tested on samp server):
![image](https://user-images.githubusercontent.com/13169094/164895974-9fecdbde-f108-47b6-91c2-932f7bb60c31.png)

# open.mp server version

[Build 2](https://github.com/openmultiplayer/server-beta/releases/tag/build2)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
The player state is changed inside TogglePlayerSpectate. 
I'll change that, it might introduce bugs.
Fixed next build.

**Comment by NexiusTailer** [comment]
> The player state is changed inside TogglePlayerSpectate.

It is. This function is called in a timer, but has applied before timer called. That's the single problem.

**Comment by NexiusTailer** [comment]
The problem is relevant again after updating to build 7.

**Comment by AbdulOmarCR** [comment]
I would like to see the difference of time when the timer is called and the player state changes.
