### ISSUE TITLE
[BUG]: Random Crashes

### ISSUE THREAD

**Issue by realhus** [openmultiplayer/server-beta-old#42]
# Description

My game randomly freezes. 
Warning(opcode 0x38B): Exception 0xC0000005 at 0x4C8F24

# How to reproduce this bug

Unfortunately, I couldn't reproduce it. it just happens randomly. 

# Relevant log output

ChatLogs : Warning(opcode 0x38B): Exception 0xC0000005 at 0x4C8F24
Nothing in server logs

# open.mp server version

Beta 2

# Operating system or distribution

Windows11

# Contact information

sus#8803 in discord

# Additional information
The server doesn't crash. my game freezes and I have to exit it with the task manager. I cannot play for 1minute straight without crashing. I tried to reproduce it but couldn't, it happens randomly
I don't encounter this in SAMP. No op-codes on samp are shown

**Comment by realhus** [comment]
Resolved after the 3rd beta. thanks

**Comment by AmyrAhmady** [comment]
All I can tell is it's related to vehicles, and most likely related to vehicle upgrades, such as components and mod
Would be really great if you find a way to reproduce this for us

**Comment by realhus** [comment]
> All I can tell is it's related to vehicles, and most likely related to vehicle upgrades, such as components and mod Would be really great if you find a way to reproduce this for us

I'm still trying to reproduce it. 
here are some things I tried
1- removed all vehicle components by hooking addvehiclecomponent function and making it return 0. The game still crashed.
2- I totally removed all vehicles on the server , the crash is gone
3- I loaded the same vehicles again using a filterscript, it didn't crash
4 - I joined the server from android (without removing vehicles)  it didnt crash 
it occurs only at one specific location in the map. might be due to too many vehicles in the same area. I'm not sure . I'll update you if I find something

**Comment by AmyrAhmady** [comment]
Thanks

**Comment by realhus** [comment]
I was able to reproduce it with this script.
just run this gamemode and use /SF command to teleport to an area with vehicles. It crashes for me in open.mp and works fine in samp. 

[bare.txt](https://github.com/openmultiplayer/server-beta/files/8568081/bare.txt)

I think it crashes when there are too many vehicle models loaded in a specific area 


Crash

```
AddVehicle(id,Float:x,Float:y,Float:z,Float:rz,c1=-1,c2=-1,c=60)
{
   return CreateVehicle(id,x,y,z,rz,c1,c2,c,false);
}
```

No Crash

```
AddVehicle(id,Float:x,Float:y,Float:z,Float:rz,c1=-1,c2=-1,c=60)
{
   return CreateVehicle(411,x,y,z,rz,c1,c2,c,false);
}
```

**Comment by AmyrAhmady** [comment]
That will help a lot, thanks

**Comment by realhus** [comment]
The issue is fixed after using another downgrade patch
