### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: 

### ISSUE THREAD

**Issue by Walter-Correa** [openmultiplayer/server-beta-old#43]
# Description

*In samp I can use PawnCmd include and plugin, but open won't let me. How am I going to test if all my commands are based on PawnCMD?*

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

1. *Step one*
2. *Step two*
3. *Step three*

# Relevant log output

```
*Paste your relevant log output here!*
```

# open.mp server version

*What open.mp server version are you using?

For a development build please specify its commit hash.*

# Operating system or distribution

*Windows 10*

# Contact information

*ex. Username#1234 or email@example.com*

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by ksenonadv** [comment]
Hello. You can use the open.mp version of that plugin which you can find here:
https://github.com/AmyrAhmady/Pawn.CMD
NOTE: You need to place this in components folder, not in plugins one.
