### ISSUE TITLE
[BUG]: IsTrailerAttachedToVehicle

### ISSUE THREAD

**Issue by Sancky** [openmultiplayer/server-beta-old#45]
# Description

IsTrailerAttachedToVehicle returns true when trailer is not attached on vehicle.

# How to re-produce this bug

-

# Relevant log output

-

# open.mp server version

build 2

# Operating system or distribution

-

# Contact information

Sancky#3199

# Additional information

-

**Comment by ksenonadv** [comment]
Hello, could you please offer us more context to this issue?
When exactly this function fails to return accurate data?

**Comment by Sancky** [comment]
After i detach the trailer from the truck.

**Comment by ksenonadv** [comment]
> After i detach the trailer from the truck.

Are u using DetachTrailerFromVehicle or are you detaching in game?

**Comment by Sancky** [comment]
In game.

**Comment by ksenonadv** [comment]
Did some changes to trailer sync. I can't reproduce this anymore on my end. I will close this issue for now. If the bug is still happening after next build release please open a new one.
