### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: bcrypt_check from bcrypt_samp doesn't call the specified function

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta-old#47]
# Description

The bcrypt_check function calls a public function specified in the parameter, which does work on SA:MP server. On OMP however, it does not do that, unless you order the bcrypt plugin to be first in line of all plugins.

# How to re-produce this behavior difference

```Pawn
#include <a_samp>
#include <bcrypt>

forward testCallback3(const playerid);

public testCallback3(const playerid)
{
	print("response");
	return 1;
}

main()
{
	bcrypt_check("abc", "$2a$12$RoEMI4wrfpehBoluih5gzuJEg2l1ojaP1cFZUbf62cFL404Ma1T/6", "testCallback3", "d", 69);
}
```

# Relevant log output

N/A

# open.mp server version

open.mp server public beta build 2

# Operating system or distribution

Debian 11

# Contact information

Richano#9220
rishanogopal@gmail.com

# Additional information

This problem does not occur on the OMP server Windows version.

plugin: https://github.com/lassir/bcrypt-samp

**Comment by alextwothousand** [comment]
Try SyS's bcrypt plugin and let us know if this still occurs.
https://github.com/Sreyas-Sreelal/samp-bcrypt/

**Comment by RichanoG** [comment]
Works without problems, thanks.
