### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: GetPVarInt and probably related functions are case-sensitive

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta-old#49]
# Description

Functions like GetPVarInt and probably other related functions (haven't tested it) are case-sensitive while the documentation says that it isn't.

# How to re-produce this behavior difference

-

# Relevant log output

-

# open.mp server version

open.mp server public beta build 2

# Operating system or distribution

Debian 11

# Contact information

Richano#9220
rishanogopal@gmail.com

# Additional information

-

**Comment by NexiusTailer** [comment]
Compare it directly with the samp server to see it's really different or this can be an issue in a certain docs which need to be corrected there.

**Comment by RichanoG** [comment]
I have already tested it and it was case-insensitive on samp server, but not on omp server.

**Comment by AmyrAhmady** [comment]
Fixed, will be available in build4
