### ISSUE TITLE
[BUG]: easyDialog

### ISSUE THREAD

**Issue by TandaraAdrian** [openmultiplayer/server-beta-old#5]
Hi, easyDialog does not work for open.mp. Anything I enter in an input dialog doesn't happen, I just debugged and nothing.

Dialog_Show(playerid, DIALOG_TEST, DIALOG_STYLE_INPUT, "Test", "Test", "Submit", "Cancel");

Dialog:DIALOG_TEST(playerid, response, listitem, inputtext[])
{
	if(!response)
		return true;

	printf("%s", inputtext);
	return true;
}

**Comment by ksenonadv** [comment]
Should be fixed next build.
