### ISSUE TITLE
[BUG]: Invalid Handle Files Crash

### ISSUE THREAD

**Issue by Sancky** [openmultiplayer/server-beta-old#50]
# Description

Old bugs which are on samp server, if an invalid handle is putted on file functions which are requiring an file handle (e.g: fwrite, fread...), will cause a server crash.

# How to re-produce this bug

Invalid handle on file functions which require an file handle.

# Relevant log output

-

# open.mp server version

build 2

# Operating system or distribution

Windows

# Contact information

Sancky#3199

# Additional information

-

**Comment by alextwothousand** [comment]
Have you included fixes.inc?

**Comment by Hual** [comment]
How did you get that invalid handle in the first place?

**Comment by Y-Less** [comment]
All the file functions check the handle is non-0.  Any other ID, what are you doing?  Using a handle after `fclose`?

**Comment by Sancky** [comment]
> Have you included fixes.inc?

No, im not using it, but should be fixed anyway on omp.

**Comment by Sancky** [comment]
> How did you get that invalid handle in the first place?

Just put a random number which isn't a valid file handle.

**Comment by Sancky** [comment]
Example: 

```
public OnGameModeInit() 
{
    fwrite(File:10, "test");
    return 1;
}
```

**Comment by Alasnkz** [comment]
This is a wontfix. We check for the actual invalid status of the handle (which is 0) not a random number, that's not viably possible.
