### ISSUE TITLE
[BUG]: "Out of memory" runtime error doing http request to https resource

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#56]
# Description

Just re-checked my old "Update checker" script which made http requests to raw pastebin pages and stopped working recently because now it force switching to https page like the most other sites. But while it just returns wrong `response_code` on samp server, on omp server it behaves a little more weird.

# How to re-produce this bug

Just the main minimal part from that script to reproduce this issue:
```pawn
#include <a_samp>
#include <a_http>

forward OnUpdCheckerVersionChecked(index, response_code, data[]);

main(){}

public OnGameModeInit()
{
	HTTP(1000, HTTP_GET, "pastebin.com/raw/b1iE3i5w", "", "OnUpdCheckerVersionChecked");
	return 1;
}

public OnUpdCheckerVersionChecked(index, response_code, data[])
{
	printf("index: %d, response_code: %d, data: '%s'", index, response_code, data);
	if(response_code == 200)
	{
		if(strcmp(data, "0.4")) printf("A new version of 'Update Checker' is available: %s", data);
	}
	else print("Failed to check 'Update Checker' update :(");
	return 1;
}
```

# Relevant log output

SA-MP server
![image](https://user-images.githubusercontent.com/13169094/164987737-b0a0af92-b086-4de1-87c7-cbdeb270c228.png)

OMP server
![image](https://user-images.githubusercontent.com/13169094/164987757-9861a34b-cc5a-4f91-a667-8d58a8365560.png)

# open.mp server version

[Build 2](https://github.com/openmultiplayer/server-beta/releases/tag/build2)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
Fixed next build.
