### ISSUE TITLE
[BUG]: SetPlayerSkin inside OnPlayerRequestClass

### ISSUE THREAD

**Issue by Demo93** [openmultiplayer/server-beta-old#57]
# Description
Noticed this after i tried my Gamemode on open.mp. Got only one AddPlayerClassEx because i use a custom Skin Selection with model preview there.

Using SetPlayerSkin in ClassSelection is not working on omp. (Works with samp).
Changing it with a Command from ClassSelection is working, but as soon as you try to select a Skin it changes it to CJ again.
(If you try to select another Skin on SA-MP the Skin is still the one from SetPlayerSkin)

# How to re-produce this bug
```pawn
#include "a_samp.inc"

main() 
{
	printf("Loaded...");
}

public OnGameModeInit()
{
	AddPlayerClassEx(MAX_PLAYERS, 0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0);
}

public OnPlayerRequestClass(playerid,classid)
{
	SetPlayerPos(playerid,388.3286,-2024.4844,8.8203);
	SetPlayerFacingAngle(playerid, 90.0);
	SetPlayerCameraPos(playerid,380.4250,-2020.8900,10.2500);
	SetPlayerCameraLookAt(playerid,388.3286,-2024.4844,8.8203);
	
	// This is not Working
	SetPlayerSkin(playerid, 120);
	
	return 1;
}

// This Works when using in Class Selection
public OnPlayerCommandText(playerid, cmdtext[])
{
    if(!strcmp(cmdtext, "/setskin"))
    {
        SendClientMessage(playerid, -1, "Skin Changed");
        SetPlayerSkin(playerid, 120);
        return 1;
    }
    
    return 1;
}
```

# open.mp server version

beta build 2

# Operating system or distribution

Windows 10 Pro

# Contact information

Discord: Demo#3999

**Comment by AmyrAhmady** [comment]
Fixed in build4
