### ISSUE TITLE
[BUG]: Function not registered: GetVehiclePaintjob

### ISSUE THREAD

**Issue by ReshiramZekrom1** [openmultiplayer/server-beta-old#58]
# Description

YSF's GetVehiclePaintjob function seems not registered although it is defined in the [ysfomp](https://gist.github.com/AmyrAhmady/94a33fc502c2694032523969e7d2ee02) include.

# How to re-produce this bug

```pawn
#include <a_samp>
#include <ysfomp>

public OnFilterScriptInit()
{
	new veh = CreateVehicle(411, 2, 2, 20, 0, 1, 1, 15);
	new paintjob = GetVehiclePaintjob(veh);
	return 1;
}
```

# Relevant log output

```
loadfs test
[25/04/2022 09:45:26] [Error] Function not registered: GetVehiclePaintjob
[25/04/2022 09:45:26] [Info] [debug] Run time error 19: "File or function is not found"
[25/04/2022 09:45:26] [Info] [debug]  GetVehiclePaintjob
[25/04/2022 09:45:26] [Error] File or function is not found
[25/04/2022 09:45:26] [Info] Filterscript 'test' loaded.
```

# open.mp server version

Build 2

# Operating system or distribution

Windows 10 and Debian 9 

# Contact information

ReshiramZekrom#7809

**Comment by ksenonadv** [comment]
Could you please try GetVehiclePaintJob?

**Comment by ReshiramZekrom1** [comment]
GetVehiclePaintJob is working fine but I had to change the native in the include too otherwise I got an undefined symbol error while compiling the script

```
error 017: undefined symbol "GetVehiclePaintJob"
```

**Comment by ksenonadv** [comment]
It will be renamed GetVehiclePaintjob in the next build. You can use GetVehiclePaintJob for now.
