### ISSUE TITLE
[BUG]: game randomly crashes

### ISSUE THREAD

**Issue by iReplay23** [openmultiplayer/server-beta-old#59]
# Description
Game crashes while holding KEY_JUMP and KEY_AIM
![KqGJOWg](https://user-images.githubusercontent.com/40267090/165072482-b293e5a0-9a85-43a9-b101-eed3e987af07.png)
# How to re-produce this bug
I can't actually reproduce it, with the 03svr version works fine, without crashing. It only happens on OMP version.
# Relevant log output
Nothing in server_log, just crashes the game.
# open.mp server version
build 2. (it crashes in build 1 too)
# Operating system or distribution
Windows 10 home, 64-bit.
# Contact information
iReplay#4787
# Additional information
I also tried with a blank gamemode and it looks to work fine (without crashing). It crashes too with default GTA. I don't really know the reason why it crashes on my gamemode maybe you guys can figure out.

**Comment by iReplay23** [comment]
Solved. SetPlayerFightingStyle with an invalid style was the reason why the game crashed.

**Comment by AmyrAhmady** [comment]
Still needs to be handled on server side as well, thanks for report
