### ISSUE TITLE
[BUG]: SetPlayerCameraLookAt CAMERA_MOVE is broken

### ISSUE THREAD

**Issue by Zbyss** [openmultiplayer/server-beta-old#6]
# Description

Setting `SetPlayerCameraLookAt` `cut` parameter to `CAMERA_MOVE` has no effect (at least in class selection, I haven't tested if it matters).

# How to re-produce this bug

```pawn
public OnPlayerRequestClass(playerid, classid)
{
    SetPlayerPos(playerid, 489.3238, -1792.7379, 6.0625);
    SetPlayerFacingAngle(playerid, 354.3279);
    SetPlayerCameraPos(playerid, 485.9425 + RandomFloat(-1.0, 1.0), -1786.0959 + RandomFloat(-1.0, 1.0), 8.3840 + RandomFloat(-1.0, 1.0));
    SetPlayerCameraLookAt(playerid, 489.3238, -1792.7379, 6.0625, CAMERA_MOVE);

    return 1;
}
```

# Relevant log output

N/A

# open.mp server version

open.mp server public beta build 1

# Operating system or distribution

Microsoft Windows 11 64-bit

# Contact information

Zbyss.#2597

# Additional information

SA-MP: https://streamable.com/n6kyzo
open.mp: https://streamable.com/m71nhj

**Comment by AmyrAhmady** [comment]
Can you check if it works when player is not in class selection state? @Zbyss

**Comment by Zbyss** [comment]
It's broken regardless of the player's state.
https://streamable.com/8bshua

**Comment by ksenonadv** [comment]
Fixed next build.
