### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Dialogs caption lenght counts HEX colors

### ISSUE THREAD

**Issue by ReshiramZekrom1** [openmultiplayer/server-beta-old#60]
# Description

Dialogs' caption limit is 64 characters. Despite this limit, SA-MP lets you use even a larger caption if you're using HEX colors. OMP doesn't. The following caption is 80 characters long including HEX colors and, while in SA-MP it is shown corretly, in OMP it is truncated exactly at the 64th character.

OMP:
<img width="397" alt="omp" src="https://user-images.githubusercontent.com/17570127/165089509-c8954746-eb4c-4e52-8dc8-2dd09a45881d.png">

SA-MP:
<img width="398" alt="samp" src="https://user-images.githubusercontent.com/17570127/165089518-e9c0a187-5550-44d0-a0fe-ce8ebfd4e030.png">

# How to re-produce this behavior difference

```pawn
ShowPlayerDialog(playerid, 0, DIALOG_STYLE_TABLIST_HEADERS, "{FF0000}You{FFFFFF}Tube Search (By {FF0000}ib{FFFFFF}sp & {FF0000}Ez{FFFFFF}io_)", "asd", "Ok", ""); 
```

# Relevant log output

N/A

# open.mp server version

Build 3

# Operating system or distribution

Debian 9

# Contact information

ReshiramZekrom#7809

**Comment by Gothon369** [comment]
have you try'ed to reformat the string and add it to the parameter `caption[]`
Example:
`
new caption[128 + 1] = EOS;
format(caption, sizeof(caption), "{ffffff}This is a white and {ff0000}red title");
ShowPlayerDialog(playerid, 0, DIALOG_STYLE_TABLIST_HEADER, caption, "the tablist information", "Button1", "Button2");
` 
 if that doesn't work then yup it is an issue

**Comment by ReshiramZekrom1** [comment]
> have you try'ed to reformat the string and add it to the parameter `caption[]` Example: `new caption[128 + 1] = EOS; format(caption, sizeof(caption), "{ffffff}This is a white and {ff0000}red title"); ShowPlayerDialog(playerid, 0, DIALOG_STYLE_TABLIST_HEADER, caption, "the tablist information", "Button1", "Button2");` if that doesn't work then yup it is an issue

The sample caption you brought up is just 45 characters long. In order to reproduce the issue the caption must be longer than 64 chars which is the limit. By the way I've tried to format the string as you said but with "{FF0000}You{FFFFFF}Tube Search (By {FF0000}ib{FFFFFF}sp & {FF0000}Ez{FFFFFF}io_)" as caption and it didn't change a bit.

**Comment by AmyrAhmady** [comment]
Will be fixed in next beta build
