### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Wrong material color for SetPlayerAttachedObject and SetPlayerObjectMaterial

### ISSUE THREAD

**Issue by ReshiramZekrom1** [openmultiplayer/server-beta-old#61]
# Description

Noticed this weird behaviour involving the optional material color parameter. The color displayed on the OMP server is different than the one on the SAMP server.

This affects both SetPlayerAttachedObject and SetPlayerObjectMaterial natives.

Objects created with CreateObject don't seem to have this issue.

In the pictures all the objects are Player Objects since I'm using the Streamer.

SAMP (correct colors):
![samp](https://user-images.githubusercontent.com/17570127/165104529-713ed9e7-e9e8-40d8-9597-bde50a4b43e9.png)

OMP (wrong colors):
![omp](https://user-images.githubusercontent.com/17570127/165104548-e538af96-cfab-4bd0-a6b2-a572a6a23ea9.png)

# How to re-produce this behavior difference

```pawn
#include <a_samp>
#include <izcmd>


CMD:test(playerid, params[])
{
    SetPlayerAttachedObject(playerid, 0, 1784,1,0.2879,0.0040,0.0208,270.0000,0.0000,0.0000,1.0000,1.0000,1.7000,0xFFFFFF00,-1);//Yellow Color

    new tmpobjid;
    tmpobjid = CreatePlayerObject(playerid, 6959, 416.611755, 2515.813720, 16.155593, 0.000000, 0.000000, 0.000000, 0.0);
    SetPlayerObjectMaterial(playerid, tmpobjid, 0, 18081, "cj_barb", "ab_marble_checks", 0xFFFF0000);//Red Color

    SetPlayerPos(playerid, 393.0598,2527.9399,16.5481);
    SetPlayerFacingAngle(playerid, 248);
    return 1;
}
```

# Relevant log output

N/A

# open.mp server version

Build 3

# Operating system or distribution

Debian 9, confirmed on Windows 10

# Contact information

ReshiramZekrom#7809

**Comment by ksenonadv** [comment]
Fixed next build.
