### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: SendRconCommand calls OnRconCommand

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#62]
# Description

It was reported and supposedly fixed in the closed beta, but I still see log diffs between some rcon commands on samp & omp server.

# How to re-produce this behavior difference

GM:
```pawn
public OnGameModeInit()
{
	SendRconCommand("rcon 0");
	return 1;
}
```

FS:
```pawn
public OnRconCommand(cmd[])
{
	printf("[FS] OnRconCommand(cmd '%s')", cmd);
	return 0;
}
```

# Relevant log output

samp server:
![image](https://user-images.githubusercontent.com/13169094/165109319-f16734e8-70a2-4209-bcc0-194d8ab49152.png)

omp server:
![image](https://user-images.githubusercontent.com/13169094/165109606-cad6c3f6-bea2-44f0-beb5-8e3265cc5e0b.png)

# open.mp server version

[Build 3](https://github.com/openmultiplayer/server-beta/releases/tag/build3)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
Hello, the execution is stopped before reaching pawn event for default commands.
"rcon" is not a default command in open.mp yet. It will be implemented next build.
