### ISSUE TITLE
[BUG]: TogglePlayerWidescreen on – pickups not working + hud missing

### ISSUE THREAD

**Issue by ddanyk** [openmultiplayer/server-beta-old#64]
# Description

When is TogglePlayerWidescreen function used to toggle ON widescreen of player, hud disappears and pickups don't work, they're invisible. When is player widescreen toggled OFF it's normal again.

# How to re-produce this bug

Call function TogglePlayerWidescreen(playerid,true);
Video: https://www.youtube.com/watch?v=kByV7nLXH_4

# Relevant log output

```
N/A
```

# open.mp server version

open.mp windows server beta build 3

# Operating system or distribution

Windows 11 Pro 21H2 22000.613

# Contact information

Discord: Amas#9855

# Additional information

SA:MP client version 0.3.7-R4

**Comment by Vince0789** [comment]
This is probably impossible to fix since all this function really does is invoke an opcode in the game (specifically [02A3: SWITCH_WIDESCREEN](https://gtamods.com/wiki/02A3)) and this behaviour is likely hardcoded into the game.

**Comment by AmyrAhmady** [comment]
It's not a bug from open.mp, rather a feature for a very specific behavior in game, like Vince said, therefore it's not going to be fixed since there's no bug in the first place
