### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: RGBA format in functions that use ARGB

### ISSUE THREAD

**Issue by RodrigoMSR** [openmultiplayer/server-beta-old#65]
# Description

In functions like SetPlayerAttachedObject and SetPlayerObjectMaterial, the RGBA format is being used and not ARGB as in the SA-MP server.

# How to re-produce this behavior difference

Using that functions with ARGB format.

# Relevant log output

# open.mp server version

open.mp server public beta build 3

# Operating system or distribution

Windows 10.

# Contact information

# Additional information

**Comment by ksenonadv** [comment]
Duplicate of #61.
