### ISSUE TITLE
[BUG]: SendDeathMessage / SendDeathMessageToPlayer bug is still in build 3.

### ISSUE THREAD

**Issue by Sancky** [openmultiplayer/server-beta-old#66]
# Description

https://github.com/openmultiplayer/server-beta/issues/39#issue-1213037432

Still not working on build 3.

# How to re-produce this bug

```
public OnPlayerDisconnect(playerid, reason) 
{
    SendDeathMessage(INVALID_PLAYER_ID, playerid, 201);
    return 1;
}
```

# Relevant log output

-

# open.mp server version

build 3

# Operating system or distribution

-

# Contact information

Sancky#3199

# Additional information

-

**Comment by AmyrAhmady** [comment]
Fixed, will be in build4
