### ISSUE TITLE
[BUG]: OnPlayerRequestClass:: GetPlayerSkin(playerid) return 0

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/server-beta-old#7]
### Bug in OnPlayerRequestClass: if using GetPlayerSkin

using the PPC_Trucking gamemode in the original version, the SetSpawnInfo function uses GetPlayerSkin in the parameter that selects the skin selected in the class selection menu (**OnPlayerRequestClass**), using this, returns the skin that the player is currently selecting

`SetSpawnInfo(playerid, 0, GetPlayerSkin(playerid), x, y, z, Angle, 0, 0, 0, 0, 0, 0);`

however, when using this way, the value 0 is returned, which is the original skin of CJ

I did a test and changed **GetPlayerSkin(playerid)**, by a random value, in the case of the test, value 5, and it worked perfectly

`SetSpawnInfo(playerid, 0, 5, x, y, z, Angle, 0, 0, 0, 0, 0, 0);`

![log](https://user-images.githubusercontent.com/97456213/164316084-55f8b293-0834-4d00-b3dd-230ac2db6763.PNG)

server log exactly in OnPlayerRequestClass: GetPlayerSkin(playerid)

![sa-mp-000](https://user-images.githubusercontent.com/97456213/164316518-b01379d7-1383-4cce-ac81-5f7cbd7ee36e.png)
the selection menu shows another skin

**Comment by ksenonadv** [comment]
Fixed next build.
