### ISSUE TITLE
[BUG]: OnPlayerDeath doesn't work

### ISSUE THREAD

**Issue by sunkie25** [openmultiplayer/server-beta-old#70]
# Description

I have been working on a paintball system and when I was working at the k/d parts on OnPlayerDeath, the callback wasn't called. But, when I moved the script on a basic SA:MP server it worked perfectly. 

# How to re-produce this bug

https://www.youtube.com/watch?v=4WWOWOKVvew

![image](https://user-images.githubusercontent.com/104133148/166142360-d6f97a2c-e8b3-4893-ac11-272b9e03a166.png)

# Relevant log output
[Info] [death] irinel77z died 255
[Info] irinel77z (0) died.
[Info] [death] irinel77z died 255
[Info] irinel77z (0) died.
[Info] [death] irinelbro69 died 255
[Info] irinelbro69 (1) died.

# open.mp server version

beta build 3

# Operating system or distribution

Windows 10 x64

# Contact information

Discord: irinel77#3505

# Additional information

open.mp the best!

**Comment by ksenonadv** [comment]
As discussed on discord, the callback is working just fine. The problem is with your script that's assigning the same team to all users (which doesn't work properly on samp but does on open.mp).
