### ISSUE TITLE
[BUG]: objects not loaded in class selection (on build 3)

### ISSUE THREAD

**Issue by criticalerror99** [openmultiplayer/server-beta-old#71]
# Description

*Objects used in class selection are not loaded on build 3. (on build 2 objects were visible)*

# How to re-produce this bug

*Streamer_UpdateEx(playerid, 1957.5920,1184.6112,1151.7664, wybieralka_vw, 0);*

# open.mp server version

*public beta build 3*

# Operating system or distribution

*Microsoft Windows 11 64-bit*

# Contact information

*critical#0937*

# Additional information

***build 2***
![01-05-2022-19-24-15_gta_sa](https://user-images.githubusercontent.com/22982995/166157192-1a07d2ea-ce7c-4666-8f3c-73199cb2ad96.jpg)

***build 3***
![01-05-2022-19-25-08_gta_sa](https://user-images.githubusercontent.com/22982995/166157194-a2379f03-eeb1-47df-816e-45a0af184ed3.png)

**Comment by AmyrAhmady** [comment]
To me it looks like you are setting interior, that's why the entire world is empty, please double check and make sure you are setting player's interior to 0 or not

**Comment by criticalerror99** [comment]
I have objects in interior 0. Objects are invisible in both cases (when changing interior or not).

**Comment by AmyrAhmady** [comment]
Not objects, I'm talking about the player, because in your case even LS default map isn't loaded
talking about this:
![image](https://user-images.githubusercontent.com/34688664/167463870-0c0b27f5-2172-4d7a-9383-63be15f9b410.png)

**Comment by criticalerror99** [comment]
Fixed by moving Streamer_UpdateEx from OnPlayerConnect to OnPlayerRequestClass.
