### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Non-registered natives on server start.

### ISSUE THREAD

**Issue by mattcomeback** [openmultiplayer/server-beta-old#72]
# Description

Use a native that doesn't exist and get a weird outcome.

# How to re-produce this bug

*Tell us a how to re-produce this bug in steps for example:*

1. Declare a native that doesn't exist.
2. Use that native.
3. On server load, you get the usual function not registered.
4. The server doesn't exit but the server query doesn't update from natives that set game settings. 
    - For example:
        - SendRconCommand("password passwordhere");
        - The password is set on the server (get the invalid server password on client join) but in the browser it shows no password which means OnGameModeInit is executed, but browser data isn't set from it.

From testing, if a non-existent native is used, it reads browser data from the server config file (mapname, modename, etc).

# Relevant log output

Read above

# open.mp server version

Beta 3

# Operating system or distribution  

Windows Server 2019

# Contact information

mattcomeback#4633

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by AmyrAhmady** [comment]
I'm nit sure if I understand, but what you described here is exactly like how samp works, isn't it?

**Comment by mattcomeback** [comment]
This could be more of a behavior issue than anything.  After further testing:  

On SA-MP: when an unregistered native is used, the server halts and doesn't allow connections.  Apparently sa-mp doesn't process the entire server.cfg either.
On open.mp when an unregistered native is used, it allows the connection but the script doesn't execute (leaves you at the join screen with class selection buttons).
'

**Comment by AmyrAhmady** [comment]
It's not an "issue", your server still works on samp as well, and in server browser you get Unknown as gamemode text, in both samp and open.mp, and in both of them you can join the server

**Comment by mattcomeback** [comment]
Ok well if it isn't a bug, it's closed.  Thanks.
