### ISSUE TITLE
[BUG]: Player don't get kicked/disconnected from server after Crash

### ISSUE THREAD

**Issue by faaactz** [openmultiplayer/server-beta-old#74]
# Description
Player don't get kicked/disconnected from server after crash

# How to re-produce this bug
I can't say exactly, I'm using refreshratefix.asi to fix my refresh rate in gta and a custom timecyc, sometimes it happens that my gta is not responding and I can't even tab in the game. 

Only thing I can use in this situation is my taskbar to open the task-manager and kill the gta_sa process which is not responding.
So I've tried to simply open and minimize the gta_sa process a couple times until my gta_sa process crashes and it worked,
the server didn't kicked me. 

It appears to happen only at open.mp, on SA:MP my player got kicked/disconnected.

# Relevant log output
there is no log since the player won't disconnect

# open.mp server version
public beta build 3

# Operating system or distribution
Windows 10 64-Bit

# Contact information
factz#0586

# Additional information
-

**Comment by AmyrAhmady** [comment]
I tried crashing my GTASA game multiple times, and each time server disconnected my instance after some time (it's a timeout disconnection, you must wait for it to happen, same as samp)

**Comment by faaactz** [comment]
If you want I can make a video for you. In my case the player was still connected after 2 hours.

**Comment by AmyrAhmady** [comment]
@factz68 please after the crash you're talking about, make sure gta_sa.exe process is gone as well
not sure how it helps, but a video would be nice

**Comment by AmyrAhmady** [comment]
closing this since there has been no contact after asking for more info, if the issue still exists create another issue please
