### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Using format without parameters causes a warning.

### ISSUE THREAD

**Issue by nicolas176** [openmultiplayer/server-beta-old#75]
# Description

Using format without parameters causes a warning.

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

1. Try to do a format text to put it in a dialog without parameters and see what happens
2. 
format(DiagString,sizeof(DiagString),""CBLANCO"Escriba su contraseña y oprima en 'Ingresar'"); // This generates a warning
format(String,sizeof(String),""CBLANCO"Identifíquese por primera vez, "CINFO"%s",name);
ShowPlayerDialog(playerid,dLogear,DIALOG_STYLE_PASSWORD,String,DiagString,"Ingresar","Salir");

It shows this

# Relevant log output

```
[04:11:12] [Warning] Insufficient specifiers given to `format`: "{FFFFFF}Escriba su contraseña y oprima en 'Ingresar'" < 1
```

# open.mp server version

*What open.mp server version are you using? Latest to 5/5/22

For a development build please specify its commit hash.*

# Operating system or distribution

Windows 11 Last distribution.

# Contact information

Chessy#3003 on Discord or by Facebook (fb.me/nicoayala176)

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by ArTDsL** [comment]
Seems normal to me, if you won't gonna use any params just insert a normal dialog, use params only for strings that need concatenation, like the title (**String**)...
```pawn
ShowPlayerDialog(playerid, dLogear, DIALOG_STYLE_PASSWORD, String, "{FFFFFF}Escriba su contraseña y oprima en 'Ingresar'","Ingresar","Salir");
```
If you are using the **format** because of the color, drop it, you can set the color directly...

___

Color parameters are diferent.

**Example:**
To set in a concatenation:
```pawn
#define C_WHITE "{FFFFFF}"
ShowPlayerDialog(playerid, dLogear, DIALOG_STYLE_PASSWORD, String, C_WHITE"Escriba su contraseña y oprima en 'Ingresar'","Ingresar","Salir");
```

To set in a parameter:
```pawn
#define COLOR_WHITE 0xFFFFFFFF
SendClientMessageToAll(COLOR_WHITE, "This phrase is white!");
```

So on...

It is not a open.mp error, it's a **Pawn warning** _\^^/_

**Comment by ArTDsL** [comment]
@Hual or @AmyrAhmady 

**CLOSED** i think ^^/

**Comment by AmyrAhmady** [comment]
Doesn't matter, it is still supposed to work even if it's not the right way of printing a message

**Comment by ArTDsL** [comment]
> Doesn't matter, it is still supposed to work even if it's not the right way of printing a message

@AmyrAhmady, I came up with a ideia, when Dev use a 0 args format, work, but print a "[info]" in console saying that is not a good way! I think it could help!

**Comment by Alasnkz** [comment]
That's what this is. It is a warning already.

**Comment by ArTDsL** [comment]
> That's what this is. It is a warning already.


@Alasnkz Ohhh, so warning pops even if the function work? I thought that he only pop because of the broken missing args 😅

**Comment by ksenonadv** [comment]
Closing this, but just to be clear:

```
format(output, sizeof output, "string"); 
``` 
is working as expected.

```
format(output, sizeof output, "string", some_var); 
``` 

won't work and will give you the warning.
