### ISSUE TITLE
[BUG]: PVars bug

### ISSUE THREAD

**Issue by Sancky** [openmultiplayer/server-beta-old#76]
# Description

PVars are not removed from memory after a server restart via rcon command gmx.

# How to re-produce this bug

Set a PVar, restart the server, and after get the PVar value which is still the setted one before restart.

# Relevant log output

-

# open.mp server version

b3

# Operating system or distribution

Windows

# Contact information

Sancky#3199

# Additional information

-

**Comment by ksenonadv** [comment]
Fixed next build.
