### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: enable_rcon disabled by default?

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#77]
# Description

Starting the omp server on bt4 I see this inscription in the logs:
![image](https://user-images.githubusercontent.com/13169094/167471989-7217a068-0972-432f-8660-cda6caf8e313.png)

Having such server.cfg settings:
![image](https://user-images.githubusercontent.com/13169094/167472181-3a795965-6a2e-4502-8373-0b9220fb02fd.png)
(there is "valid" rcon_password and no any "rcon 0" option set)

At first glance, the problem caused either due to some incorrect actions when reading legacy settings (so this could be classified as a bug), or it is really now disabled by default (in this case, just a behavior difference with samp server)

# How to re-produce this behavior difference

Use server.cfg with legacy options declaring rcon_password to something (not empty) and start the server

# open.mp server version

[Build 4](https://github.com/openmultiplayer/server-beta/releases/tag/build4)

# Operating system or distribution

Windows 10 Pro (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
nex-ac is disabling it.

**Comment by NexiusTailer** [comment]
It should be time to take a good nap if that's the case ._.
Give me a couple of minutes to check, that's probably really my fault

**Comment by NexiusTailer** [comment]
Yeah, sorry for dumb issue, just missed some internal ac configs at the moment of testing
