### ISSUE TITLE
The TextDrawSetStringForPlayer native doesn't work.

### ISSUE THREAD

**Issue by lPauI** [openmultiplayer/server-beta-old#78]
# Description

*Describe the behavior difference between open.mp server and SA:MP server!*

On the SA:MP server, with YSF plugin and include works perfectly, and with the include ysfomp, on open.mp is crashing when I use this native.

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

Just use the native TextDrawSetStringForPlayer, and your srever it will be crash.

# Relevant log output

```
*Paste your relevant log output here!*
```

Is not any log output from the TextDrawSetStringForPlayer function, but i maked debugs, and the server crashs from that.

# open.mp server version

*What open.mp server version are you using?

public beta build 4

For a development build please specify its commit hash.*

# Operating system or distribution

Windows 11 64-Bit

*Tell us what operating system or distribution did you use when you did encounter this behavior difference?*

Windows 11 64-Bit

# Contact information

xPaulFTW#4537

# Additional information

.

**Comment by ksenonadv** [comment]
Fixed next build.
