### ISSUE TITLE
[BUG]: GetVehicleTrainSpeed only returns 0.0

### ISSUE THREAD

**Issue by Rodion15** [openmultiplayer/server-beta-old#79]
# Description

When creating

`CreateVehicle` or `AddStaticVehicleEx`

Does not read functions and does not return.

```
native GetVehicleColor(vehicleid, &color1, &color2 = 0);
native Float:GetVehicleTrainSpeed(playerid);
```

# open.mp server version

[build4](https://github.com/openmultiplayer/server-beta/releases/tag/build4)

**Comment by ksenonadv** [comment]
GetVehicleTrainSpeed should be used with vehicle as argument. It was corrected in ysfomp.inc

```pawn
native Float:GetVehicleTrainSpeed(vehicleid);
```

GetVehicleColor fixed in next build.

**Comment by Rodion15** [comment]
@ksenonadv 

`native Float:GetVehicleTrainSpeed(vehicleid);`

It doesn't give anything back. Just 0.0000 during the ride

`SEND_MES(playerid, -1, "%f",GetVehicleTrainSpeed(GetPlayerVehicleID(playerid)));`

**Comment by AmyrAhmady** [comment]
@Rodion15 can you make a simple small script for testing?

**Comment by Rodion15** [comment]
@AmyrAhmady 

```
#define SEND_CM 		SendClientMessage
new format_string1[228];
#define SEND_MES(%0,%1,%2,%3) \ 
	format(format_string1, sizeof(format_string1),%2,%3) && SEND_CM(%0, %1, format_string1)

SetTimerEx("UpdateSpeedometr", 120, 1, "d", playerid);

public: UpdateSpeedometr(playerid)
{
	if(IsPlayerInAnyVehicle(playerid) && GetPlayerVehicleSeat(playerid) == 0){
        SEND_MES(playerid, -1, "%f",GetVehicleTrainSpeed(GetPlayerVehicleID(playerid)));
	}
```

**Comment by Rodion15** [comment]
`GetVehicleTrainSpeed`

This one is for the train, not the car.
