### ISSUE TITLE
 where is source code 

### ISSUE THREAD

**Issue by Mandofskii** [openmultiplayer/server-beta-old#80]

**Comment by AmyrAhmady** [comment]
It will be open source after public beta phase

**Comment by Mandofskii** [comment]
@AmyrAhmady میشه یه زمان تقریبی بگی واسش لطفا ؟

**Comment by AmyrAhmady** [comment]
@Mandofskii مشخص نیست در حال حاضر
زمانش میشه زمانی که ایشو ها بیشترش فیکس بشه و دیگه یه مدتی ما ریپورت جدیدی نداشته باشیم
اگه میخوای بیشتر حرف بزنیم دیسکور بهم پیام بده iAmir#8100 یا تلگرام @findmebih
