### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Newly spawned vehicles spawning at the previous vehicle coordinates

### ISSUE THREAD

**Issue by ZantetsukenGT** [openmultiplayer/server-beta-old#82]
# Description

Under uncertain circumstances when using a combination of `GetPlayerPos`, `GetPlayerFacingAngle`, `CreateVehicle` and `PutPlayerInVehicle`, it results in a newly spawned vehicle with the coordinates of the immediate previously spawned vehicle, ignoring the current `GetPlayerPos`, `LinkVehicleToInterior` and `SetVehicleVirtualWorld` are less probably to be related, this behavior is not present in samp.

video footage:

please take a look at the stuntplane I spawned at [0:25](https://youtu.be/oyJ20ChMrLQ?t=25) and then skip to [1:23](https://youtu.be/oyJ20ChMrLQ?t=83) where I essentially drop it to waste, its final location is in the middle of this corridor.

![](https://i.imgur.com/uMmVofv.png)

then for an unrelated server ddos situation, please skip to [12:50](https://youtu.be/oyJ20ChMrLQ?t=770) where I spawn another stuntplane and it spawns at the coordinates of the previous stuntplane I had spawned, you can close the video now.

# How to re-produce this behavior difference

This is yet another bug I wasn't able to reproduce on a snippet (execution on windows), it only happened randomly on a live server (linux), the complete gamemode uses y_hooks to hook into CreateVehicle to add the newly created vehicle id to an iterator and they are destroyed later on, such functionality is completely unrelated to spawning a new car and placing the player in it on the spot.

But if you want to try the snippet here it is 

1. Ensure YSI 5.x and samp-stdlib dependencies
2. Define the `/v [id]` cmd using the provided snippet
3. Go ingame and start spawning some cars with `/v [id]`, (513 stuntplane, 522 nrg, etc)

snippet:
```pawn
#pragma dynamic 3500000
#define CGEN_MEMORY 40000
#define MAX_PLAYERS 10
#define YSI_NO_HEAP_MALLOC

#include <a_samp>
#include <YSI_Players\y_groups>
#include <YSI_Visual\y_commands>
#include <YSI_Coding\y_va>

main(){}

public OnScriptInit()
{
	Group_SetGlobalCommand(Command_GetID("v"), ALLOW);
}

YCMD: v(playerid, params[], help)
{
	if (help)
		return 1; //SendCommandHelpMessage(playerid, "spawn a vehicle.");
	if (isnull(params) || !IsNumeric(params))
		return 1; //SendUsageMessage(playerid, "/v [ID]");

	new veh = strval(params);
	if (veh < 400 || veh > 611)
		return 1; //SendErrorMessage(playerid, "Invalid Vehicle Name."); //In samp there is no vehile with ID below 400 or above 611

	new Float: Pos[4];
	GetPlayerPos(playerid, Pos[0], Pos[1], Pos[2]);
	GetPlayerFacingAngle(playerid, Pos[3]);

	if (IsPlayerInAnyVehicle(playerid))
	{
		DestroyVehicle(GetPlayerVehicleID(playerid)); //If you are already in a vehicle and use /v, it will destroy that vehicle first and spawn the new one.
	}

	new MyVehicle = CreateVehicle(veh, Pos[0], Pos[1], Pos[2], Pos[3], -1, -1, -1); //Creates the specific vehicle u were looking for (veh).
	new plate[MAX_PLAYER_NAME + 1];
	GetPlayerName(playerid, plate);
	SetVehicleNumberPlate(MyVehicle, plate);
	LinkVehicleToInterior(MyVehicle, GetPlayerInterior(playerid));		//Links vehicle interior to the current player interior.
	SetVehicleVirtualWorld(MyVehicle, GetPlayerVirtualWorld(playerid)); //Sets vehicle virtual world the the current virtual world of the player.
	PutPlayerInVehicle(playerid, MyVehicle, 0);							//Puts player in the driver seat.

	AddVehicleComponent(MyVehicle, 1025); // Offroad wheels
	AddVehicleComponent(MyVehicle, 1087); // Hydraulics

	va_SendClientMessageToAll(-1, "%s has spawned a vehicle", plate);
	return 1;
}

```

# Relevant log output

```
No output since there's no errors
```

# open.mp server version

*build 4*

# Operating system or distribution

*Debian 11*

# Contact information

discord: *Zantetsuken#2220*

# Additional information

The full command's src is defined in this [file](https://github.com/ZantetsukenGT/AttDef/blob/main/modules/commands/v.inc), but for the snippet I removed unrelated code.

**Comment by AmyrAhmady** [comment]
@ZantetsukenGT can you confirm that it only happens when you are using YSI?

**Comment by ZantetsukenGT** [comment]
The hooks im talking about looked something like [this](https://github.com/ZantetsukenGT/AttDef/blob/main/legacy/modules/impl/hooking/vehicle.inc#L20)

I will make more tests on my tournament-grade open.mp server 🤥

**Comment by AmyrAhmady** [comment]
I'm not able to reproduce it, if it was just a one time thing maybe server was just slow or out of order while sending network packets to destroy the car and replace it with a new one, create a new one if you have managed to find a working repro method
