### ISSUE TITLE
[BUG]: GetPlayerAnimationIndex

### ISSUE THREAD

**Issue by lPauI** [openmultiplayer/server-beta-old#83]
# Description

If you are in a vehicle, your GetPlayerAnimationIndex it will be 1189 (in omp), and if you are in a vehicle, your GetPlayerAnimationIndex it will be 0 (in sa:mp).

# How to re-produce this behavior difference

Enter on a vehicle and check your GetPlayerAnimationIndex

# Relevant log output

```
*Paste your relevant log output here!*
```

# open.mp server version

*What open.mp server version are you using?

build 4

# Operating system or distribution

Windows 11 64-Bit

# Contact information

xPaulFTW#4537
lascupg13@gmail.com

# Additional information

**Comment by AmyrAhmady** [comment]
Fixed next build
