### ISSUE TITLE
[BUG]: GetWeaponName for reasonid 53 and 54

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#86]
# Description

GetWeaponName mess up a name for reason id 54 (it is "Splat", but it tells "Drowned") and tells "Invalid" for reason id 53 (it is "Drowned")

# How to re-produce this bug

```pawn
main()
{
	for(new i, gunname[32]; i <= 54; i++)
	{
		GetWeaponName(i, gunname, sizeof(gunname));
		printf("%d: '%s'", i, gunname);
	}
}
```

# Relevant log output

samp server
```
<...>
[16:54:24] 53: 'Drowned'
[16:54:24] 54: 'Splat'
```

omp server
```
<...>
[16:54:29] [Info] 53: 'Invalid'
[16:54:29] [Info] 54: 'Drowned'
```

# open.mp server version

[Build 4](https://github.com/openmultiplayer/server-beta/releases/tag/build4)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

# Additional Information

There is also a behaviour diff in that samp server clears the string with weapon name when the ID passed invalid or unknown, while omp always write "Invalid" in that string.

**Comment by ksenonadv** [comment]
Fixed next build.
