### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Different chatlog format comparing to samp server

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#87]
# Description

chatlog format is a little bit different comparing to samp server in just one detail: samp has `[nickname]: message` while omp has `nickname: message` log format

# How to re-produce this behavior difference

Enable chatlogging and write anything in the chat

# Relevant log output

omp
![image](https://user-images.githubusercontent.com/13169094/169549270-f7891751-3797-4052-9559-9797ae73f73c.png)

samp
![image](https://user-images.githubusercontent.com/13169094/169549478-8b324cdb-436c-4c1a-a63b-437a0c6f3570.png)

# open.mp server version

[Build 4](https://github.com/openmultiplayer/server-beta/releases/tag/build4)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
Fixed next build.
