### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Limited number of rules displayed in masterlist comparing to samp server

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#89]
# Description

Limited number of rules is displayed in masterlist comparing to samp server

# How to re-produce this behavior difference

Start an omp server and then samp server, open samp client and update both servers in server browser.
Look at number of rules in a list which sends samp and omp server.

# Relevant log output

Any samp server always send the full list of rules:
![image](https://user-images.githubusercontent.com/13169094/169574862-a54eb13a-050d-499c-874b-13af73da137e.png)

But not any omp server does
![image](https://user-images.githubusercontent.com/13169094/169575009-2ccd6f7e-dfaa-4693-b880-ff48388f19b7.png)

# open.mp server version

[Build 4](https://github.com/openmultiplayer/server-beta/releases/tag/build4)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
Fixed next build.
