### ISSUE TITLE
[FEATURE]: Various little fixes which worth adding

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#90]
# Feature request

SA-MP has a lot of bugs, many of them became "features" or now used by a lot of scripts for something to be called a feature and fixing them means break something there. But there is also lots of minor bugs which constantly gives only problems and hardly can be used for any trick or represent something originally conceived.

One important thing is that I list mostly those fixes which cannot (or it's unreasonable to) be fixed by any pawn scripts without memhack plugins. And of course all these fixes don't rely on client side. Here is the list:

1. Fix for SetVehicleZAngle and SetVehicleVelocity which sends player RPC only for the last player who interacted with the vehicle (a player who was the last driver, for example), even after his disconnection
2. Fix for DisableInteriorEnterExits using which the door yellow markers won't be reenabled if the gamemode is changed (need to send outcoming RPC InitGame for all connected players with right value of InteriorEnterExits parameter)
3. Fix for GetPlayerSkin which returns the old skin if the player was spawned through SpawnPlayer function
4. Fix for OnPlayerSelectedMenuRow and OnPlayerExitedMenu which could be processed even if playerid wasn't valid
5. Fix for OnPlayerRequestClass which doesn't really reject picked class info by returning 0 in this callback
6. Fix for GetTickCount and tickcount which have weird behavior on Windows (both return the uptime of the physical server)

# Contact information

Nexius#2253

# Additional information

**This list assumes that omp works in each of the given cases in the same way as compared to samp and it still wasn't checked on omp server.** So, I ask all other beta testers (if you have the time and interested in that), to check it out and confirm/deny whether any of listed samp bugs here as well.

**Comment by NexiusTailer** [comment]
Please also remove `bug` label as there is no [FEATURE] template in this repo yet, so I picked bug template and got this label attached.

**Comment by xs1vr** [comment]
> Please also remove `bug` label as there is no [FEATURE] template in this repo yet, so I picked bug template and got this label attached.

'Don’t see your issue here? Open a blank issue.'

xd

**Comment by NexiusTailer** [comment]
> > Please also remove `bug` label as there is no [FEATURE] template in this repo yet, so I picked bug template and got this label attached.
> 
> 'Don’t see your issue here? Open a blank issue.'
> 
> xd

Picked that only because it has pre-made "Contact information" field so I thought I'd save time with this lol

**Comment by NexiusTailer** [comment]
I can already confirm at least one crash (using `Kick` in `OnPlayerDisconnect`):
[omp_minidump.zip](https://github.com/openmultiplayer/server-beta/files/8747714/omp_minidump.zip)

**Comment by AmyrAhmady** [comment]
1. SetVehicleZAngle is now broadcasted to everyone, and SetVehicleVelocity is only sent if driver is valid (it can not be broadcasted due to client's behavior)
2. Renabling interior enter exit doesn't make sense when it is disabled once, instead of that we should create a function to enable it, like `EnableInteriorEnterExits`, which will be added later
3. Already fixed in open.mp
4. There's no way you call the callbacks with invalid player id, and if you meant invalid menu id, it is already handled in open.mp
5. I am not sure what you mean by the `OnPlayerRequestClass`, maybe you can test it to see if it's still an issue in open.mp
6. Same as 5

**Comment by NexiusTailer** [comment]
@AmyrAhmady thanks for checking all this stuff!

> There's no way you call the callbacks with invalid player id, and if you meant invalid menu id, it is already handled in open.mp

In samp, actually it is. You (as a player) can call OnPlayerSelectedMenuRow and OnPlayerExitedMenu with invalid `playerid` if you are still in the process on connection (i.e. not fully connected yet). Check any other's callback validation checks and compare them with those in these two callbacks by IDA.

***

Will check this myself later, but I want to clarify what I meant here if you ask:

> I am not sure what you mean by the OnPlayerRequestClass, maybe you can test it to see if it's still an issue in open.mp

You can spoof RequestClass RPC to the samp server anytime you want it and even if gamemode will reject class changing in OnPlayerRequestClass callback (by returning 0), next spawn this player will have all the spawn data from a class he spoofed, IIRC the skin will definitely change and it was a way to cheat any needed skins (which will be visible for all players) if the server has them in some of the class info. Now for that reason I use [Pawn.RakNet packet dropping in my ac](https://github.com/NexiusTailer/Nex-AC/blob/master/src/v1.9.59/nex-ac.inc#L8704) for this specific RPC instead of rejecting in a native callback just to prevent this thing.

> Same as 5

I don't remember exactly what works correct (GetTickCount or tickcount) and what works incorrect, but there is a known issue on windows server when you use time checks based on GetTickCount, that even if you just started your samp server, but your physical server was running about 3-4 weeks, your GetTickCount will be initially overflow. Sounds logical enough according to the [wiki description](https://team.sa-mp.com/wiki/GetTickCount), but running the same code on linux it hasn't such problems if the server just started, but only overflows if the samp server was running for a really long time. So, making assumptions based on that, either tickcount has the same behaviour with GetTickCount on windows/linux or it's also messed up and working differently on two OSes, like GetTickCount, but with the opposite behaviour.

**Comment by AmyrAhmady** [comment]
> In samp, actually it is. You (as a player) can call OnPlayerSelectedMenuRow and OnPlayerExitedMenu with invalid playerid if you are still in the process on connection (i.e. not fully connected yet). Check any other's callback validation checks and compare them with those in these two callbacks by IDA.

Well then, it's not possible in open..mp because packet/rpc processing doesn't happen before fully initializing player and adding them to pools

I'll checkout the rest, thanks

**Comment by AmyrAhmady** [comment]
Fixed in build 6
