### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Undocumented OnPlayerConnect and OnPlayerDisconnect calls

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#94]
# Description

As it was discussed before, players aren't being connected to the server when random filterscript just loaded and aren't being disconnected when it unloads, but it calls connect and disconnect events like they does. These fake calls can break scripts (by double call it where somebody calls them manually or if user do all needed actions in OnFilterScriptInit/Exit by a players loop and this calls will again double do those actions) so that should be disabled by default or moved to something like separate "fixes" component (to have possibility to disable it for users) and documented in readme.

# How to re-produce this behavior difference

1. Make a filterscript with basic logging
```pawn
public OnFilterScriptInit()
{
	print("[FS] OnFilterScriptInit()");
	return 1;
}

public OnFilterScriptExit()
{
	print("[FS] OnFilterScriptExit()");
	return 1;
}

public OnPlayerConnect(playerid)
{
	printf("[FS] OnPlayerConnect(playerid %d)", playerid);
	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	printf("[FS] OnPlayerDisconnect(playerid %d, reason %d)", playerid, reason);
	return 1;
}
```

2. Start a server, connect to it and `loadfs <yourFilterScript>` via console or in-game

# Relevant log output

samp server:
![image](https://user-images.githubusercontent.com/13169094/169653224-07aef979-d609-4ecc-827f-d8da7a6e0d5a.png)

omp server:
![image](https://user-images.githubusercontent.com/13169094/169653169-db74574b-eb71-4790-95d9-d7a103733f92.png)

# open.mp server version

[Build 4](https://github.com/openmultiplayer/server-beta/releases/tag/build4)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by Y-Less** [comment]
Well there is no readme yet, so most things aren't documented.  We fully intend to document these things for the full release, and in the meantime you can always refer to the fixes.inc readme:

https://github.com/pawn-lang/sa-mp-fixes/

**Comment by NexiusTailer** [comment]
I'm about this repo's readme, so, this at least should be added here as one of the possible-breaking change:
![image](https://user-images.githubusercontent.com/13169094/172062613-2d780728-7fb0-4343-b059-aa4fc6aefacb.png)

**Comment by Y-Less** [comment]
Done.
