### ISSUE TITLE
[BUG]: samp-npc doesn't work

### ISSUE THREAD

**Issue by BrainerSP** [openmultiplayer/server-beta-old#95]
# Description

*Bots (ConnectNPC) do not connect to the open.mp server, but work on the samp-server.
(I have adjusted the max_bots and maxnpc values.)*

# How to re-produce this bug

*I created a simple script that allows you to run the bot and compare the results on both servers. - [DOWNLOAD](https://drive.google.com/file/d/1NITVYaaPZSfs_XMeR2GUFZwS7ek8BINP/view?usp=sharing)*

# open.mp server version

[Beta 4](https://github.com/openmultiplayer/server-beta/releases/tag/build4)

# Operating system or distribution

*Windows 10*

# Contact information

*lexon232@gmail.com*

**Comment by AmyrAhmady** [comment]
Did you add `samp-npc.exe` to your server directory?

**Comment by BrainerSP** [comment]
> Did you add `samp-npc.exe` to your server directory?

Yes. It's also in the archive.

**Comment by AmyrAhmady** [comment]
fixed in next build
