### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Delete stupid Kalcor's ideas

### ISSUE THREAD

**Issue by yegorburylov** [openmultiplayer/server-beta-old#96]
# Introducing

Hi, guys!
I am amazed (in a good way) by your work on a new breath for GTA:SA.
I plan to make my gamemode on your server.
And for all the time, while I doing anything, two things always pissed me off.

P.S. I have bad English, so I write through a translator :)

# Description

1. Skin selection when connecting a player (three buttons below, OnPlayerRequests);
2. Using a crappy SetSpawnInfo before calling OnPlayerSpawn.

Can you work on that and get those medieval ideas out of the way?

# Contact information

goffie2000@gmail.com

# Additional information

My gamemode is only written in very early stages, so I want to move to your server. What can you advise or warn me about?

**Comment by xs1vr** [comment]
How do you expect the server to know where to spawn the player without spawn info previously set? 😅

Removing skin selection a.k.a player classes are is a no-brainer because
a) it'd brrak the compatibility
b) it's good.

**Comment by ksenonadv** [comment]
We obviously want to keep them for now because we're backwards compatible.
You can get rid of class selection using TogglePlayerSpectating. 
Also you can use, or not SetSpawnInfo, it's your choice.

**Comment by yegorburylov** [comment]
> How do you expect the server to know where to spawn the player without spawn info previously set? 😅

After executing the callback

> Removing skin selection a.k.a player classes are is a no-brainer because
> a) it'd brrak the compatibility
> b) it's good.

For example, my gamemode does not need this "good" at all. It only complicates my work, forcing me to get around it somehow.

> You can get rid of class selection using TogglePlayerSpectating.

Already. But is it really worth it?

> Also you can use, or not SetSpawnInfo, it's your choice.

Already tired of fixing something all the time
