### ISSUE TITLE
[FEATURE]: Make clearer difference between console [Error] and [Warning] messages

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#97]
# Description

Not a "real bug" or behaviour diff with samp, but I noticed that ```[Error]``` console messages usually print some code runtime errors or other issues to be fixed in your scripts, while ```[Warning]``` can be printed on some client's actions or similar (not so critical) stuff.

Today I noticed that even "failed RCON login" prints with a error tag, so, I can assume there are lot more such messages which is more appropriate to be warnings, not errors. Would be nice to check all the current console messages and set appropriate tags for all of them.

![image](https://user-images.githubusercontent.com/13169094/170010593-6ef0f3f4-2cfc-49b0-987b-3e7d7045d91c.png)

# Contact information

Nexius#2253

**Comment by NexiusTailer** [comment]
Btw, at least one warning message from samp was ported as-is:
```
[Info] Warning: Minimum time between new connections (<number>) exceeded for <ip>. Ignoring the request.
```
So it has `[Info]` tag while it's a warning and at the same time it double clarifies it's real tag which is no sense.

**Comment by ksenonadv** [comment]
Fixed next build.
