### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: SendClientMessageToAll doesn't work in OnGameModeExit

### ISSUE THREAD

**Issue by Zbyss** [openmultiplayer/server-beta-old#98]
# Description

`SendClientMessageToAll` doesn't work in `OnGameModeExit` on open.mp server if it's called on server shutdown (the message doesn't display to connected players). Everything works fine, if the callback is called during mode end.

# How to re-produce this behavior difference

MCVE:
```pawn
#include <a_samp>

main() {}

public OnGameModeExit()
{
    SendClientMessageToAll(-1, "Hello world!");
    return 1;
}
```
Connect to the server and shut down it using `exit` in console (or by `/rcon exit`).

# Relevant log output

N/A

# open.mp server version

[open.mp server public beta build 5](https://github.com/openmultiplayer/server-beta/releases/tag/build5)

# Operating system or distribution

Microsoft Windows 11 64-bit

# Contact information

Zbyss.#2597

# Additional information

N/A

**Comment by AmyrAhmady** [comment]
I'm not really sure why you even need this, and it's not really reliable, `OnGameModeExit` is called as the last step, players are already left/disconnected and networking is closed.
Closing this for now, we'll see if it's needed in our internal chat, but most likely we won't "fix" anything
