### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: Textdraw preview model rotations

### ISSUE THREAD

**Issue by sunkie25** [openmultiplayer/server-beta-old#99]
# Description
On the SA:MP server when I create a textdraw with model preview and I rotate the textdraw, on the open.mp server the rotations are different.

SA:MP (which is correctly rotated):
![image](https://user-images.githubusercontent.com/104133148/170070529-7eec8fd1-28cf-495f-8662-2db3191a91b6.png)

open.mp:
![image](https://user-images.githubusercontent.com/104133148/170070660-e6f3c498-2636-451d-8e5d-e4fdd5539019.png)

# How to re-produce this behavior difference

https://pastebin.com/kUj1uX7Q

# Relevant log output
None.

# open.mp server version

beta build 5

# Operating system or distribution

Windows 10 x64.

# Contact information

irinelbro69@gmail.com
Discord: irinel77#3505

# Additional information

-

**Comment by AmyrAhmady** [comment]
Please give us a minimal example script, with a screenshot of how it looks in samp

**Comment by sunkie25** [comment]
> Please give us a minimal example script, with a screenshot of how it looks in samp

https://pastebin.com/kUj1uX7Q

**Comment by ksenonadv** [comment]
Fixed next build.
